### ISSUE TITLE
系统路径 , input文件编码 , 以及转换简拼问题

### ISSUE THREAD

**Issue by salonz** [boomker/rime-fast-xhup#1]
感谢分享这么好用的模块, 使用中碰到一些问题和疑问, 我是新手小白, 有的问题可能比较初级, 请见谅
1. flypy_dict_generator_new.py 文件顶部引用外部模块中的
    from pathlib import PosixPath as pp
    PosixPath是Linux下的路径, windows下使用要改成 WindowsPath , 否则会出错, 之前在另一个repo中提到的问题就是这个原因.查了资料似乎可以 from pathlib import Path as pp, 这样可能兼容性好一些, 我没有linux系统设备, 无法测试, win10下是可以的.

2. 还是和系统有关, windows下默认读取文件是用的GBK编码, 一开始用utf-8编码的文件一直出错, 只好先把要转换的文件改成gbk编码. 我想把读取模式改成utf-8, 但是代码中没找到input文件在哪里添加'encodeing'参数....(新手见笑了)

3. 关于转简拼功能, 我理解是会把 '简单 jian dan 1' 转换成 '简单 jd 1' ,可是实际上转换成了 '简单 jiandan 1, 不知道就是这样设计的还是我哪里参数没有设置对.

**Comment by boomker** [comment]
> 1.  osixPath是Linux下的路径, windows下使用要改成 WindowsPath
> 2. 我想把读取模式改成utf-8
> 3. 关于转简拼功能
------

第一个问题:  我这边更新了代码,   兼容了 windows

 第二个问题: 更新了代码, 你那边再测试下

第三个问题,  我这边测试下来是没问题的,  截图如下,  不知道是否是你系统或者是命令行参数问题  
<img width="781" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/eeadbcbb-dbc9-4636-9ce7-2691a58b02f3">

**Comment by salonz** [comment]
> 第一个问题: 我这边更新了代码, 兼容了 windows
> 
> 第二个问题: 更新了代码, 你那边再测试下
> 
> 第三个问题, 我这边测试下来是没问题的, 截图如下, 不知道是否是你系统或者是命令行参数问题

这个pypinyin_dict 好像没有这个模块, 运行出错了
![image](https://github.com/boomker/rime-fast-xhup/assets/73030356/de73b13c-2a2d-4733-837d-a633ad5611c8)

**Comment by salonz** [comment]
> 第三个问题, 我这边测试下来是没问题的, 截图如下, 不知道是否是你系统或者是命令行参数问题
 
原因找到了, 是因为之前没用 -c 参数, 但是加了 -c 后又报错, 说我没有安装 pypinyin 库, 可是实际上是装了的, 不用 -c 参数就可以正常运行, 最后发现是下面这段代码的问题
![image](https://github.com/boomker/rime-fast-xhup/assets/73030356/95c4798e-1dc7-4eba-bb45-1edb5369c871)
这里参数用了 "python3", 改成 "python" 就正常了, 可能又是windows系统的原因, 不知道Linux系统改成 "python" 后是否可以运行.
其他没什么问题了 , 感谢！
