### ISSUE TITLE
win11 部署错误 error

### ISSUE THREAD

**Issue by king-ta** [boomker/rime-fast-xhup#10]
![image](https://github.com/boomker/rime-fast-xhup/assets/63304016/fa7192ed-78e0-4131-9e48-c9abcff2f94d)
为什么Rime后面目录会用斜杠。。。好奇怪

**Comment by boomker** [comment]
已经修复，拉取最新的提交更新后再尝试下。
需要说明的是：这个词库文件`flypy_phrase` 是用来自动上屏的短语词汇，需要取消[主配置文件](https://github.com/boomker/rime-fast-xhup/blob/7e190a6f495918b5320499cb1f790d7ea1d4c07d/flypy_xhfast.schema.yaml#L13C1-L13C1)中的这行注释：
`    # - flypy_phrase    # 中文词库 - 现代汉语词典 & 清华开源词库`， 然后重新部署。
因为是短词自动上屏，对于喜欢长句输入的同学可能不太喜欢，我就默认注释掉了。
