### ISSUE TITLE
请问怎么实现音形的单字输入模式排在所有词前面

### ISSUE THREAD

**Issue by zhiliao11** [boomker/rime-fast-xhup#101]
想先实现小鹤音形的单字输入模式，然后在接双拼或者词组之类的其他功能，请教大佬，这能实现吗，或者添加，谢谢啦

**Comment by boomker** [comment]
你的需求是：
单字候选项优先放在前面，其次是词组候选项对吧，这种模式只适合打单字，可以做成一个快捷键来切换到这种模式
这种模式我的设想：限定最多4码，4码唯一就自动上屏
可以考虑支持

**Comment by zhiliao11** [comment]
谢谢大佬，4码够了，本来按tab键可以完成的，但奈何有时输入人名比较多，大佬的方案非常方便，不想打断连续性换其他方案，所以有此一问。能连续输入单字，又能候选词组是非常棒的体验，👍，最好能在配置文件中有选项能改，有时在手机rime中输入也很方便，像tab键一样，虽然现在的tab还有点小问题。支持大佬，祝一帆风顺

**Comment by boomker** [comment]
更新了一版，实现了全局控制的单字模式，默认关闭，可以通过快捷键 `Ctrl-s` 启用(全局所有应用软件生效)
也可以在，配置文件里开启，配置项  看这里：
https://github.com/boomker/rime-fast-xhup/blob/9b597fbe2fc5472a6642cd6f2f3a1b5681efc1c1/flypy_xhfast.custom.yaml#L141-L142
