### ISSUE TITLE
在截图页面上打字，无法显示出候选项，只会显示出录入的拼音

### ISSUE THREAD

**Issue by haosemusi** [boomker/rime-fast-xhup#102]
尝试换了其它的方案，能正常展示候选框，不知道这个属于是客户端的问题还是配置的问题了

<img width="960" alt="image" src="https://github.com/user-attachments/assets/c68f9ba7-8a71-4751-b136-65bd3de0a865">

**Comment by boomker** [comment]
输入法程序重启试试，你那边用的是什么客户端， Mac 版鼠须管没有这个问题

**Comment by haosemusi** [comment]
多次排查，发现应该是截图软件ishot pro的问题，换了个其他截图软件就正常了。
