### ISSUE TITLE
误删词(ctrl+x/d)后，如何恢复？

### ISSUE THREAD

**Issue by transread** [boomker/rime-fast-xhup#104]

**Comment by boomker** [comment]
如果是通过组合键 `Ctrl+d` 或 `Ctrl+x`  来删词的话，可以通过在[记录文件](https://github.com/boomker/rime-fast-xhup/tree/c4f90ad66f1e695fddeb0ee209fc3f52109dc321/lua/cold_word_records)里找到对应的条目并删除即可
