### ISSUE TITLE
如何取消单词和部分符号后面自动添加空格

### ISSUE THREAD

**Issue by edison0808** [boomker/rime-fast-xhup#11]
如题，请问作者大大要怎么修改才能取消这个功能呢？

**Comment by boomker** [comment]
主配置文件里删除或注释掉这几行：
48    - lua_processor@word_append_space_processor
97    - lua_filter@word_append_space_filter

---

彻底移除这个功能，在`rime.lua` 里注释或删除
<img width="519" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/1e7358a7-5589-41c6-acc9-47ab3b01baeb">

**Comment by edison0808** [comment]
已解决 谢谢大佬
