### ISSUE TITLE
词库太大了，部署了1个小时还没有成功

### ISSUE THREAD

**Issue by ZhuYanQing2** [boomker/rime-fast-xhup#13]
词库太大了，部署了1个小时还没有成功

**Comment by boomker** [comment]
这个视机器硬件配置决定，16内存，部署3分钟之内。
你可以把主词库[文件](https://github.com/boomker/rime-fast-xhup/blob/33c82387e8a8ac0d4517a6f81c539cdf3dafd1de/flypy_xhfast.dict.yaml)里的这些给注释掉：
<img width="499" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/c9ed9059-d23f-4ef1-8255-6d9309dbfa28">

**Comment by ZhuYanQing2** [comment]
非常感谢你的回答，已经注释后部署成功了，很棒的方案，期待一直维护下去
