### ISSUE TITLE
FR:  符号智能输入

### ISSUE THREAD

**Issue by boomker** [boomker/rime-fast-xhup#14]
最后有一个小需求，如果您感兴趣可以考虑一下，不感兴趣您可以直接忽略

目前有了一个数字后面的句号和冒号自动转半角，能否实现这样一个功能，连续两个全角就自动转为一个半角，大致实现思路是这样的，以逗号为例：
记录提交历史，在按下全角逗号时，如果上一个提交为全角逗号，那么发送一个退格键和一个半角逗号,

这个我在 rime 官方 issue 里提过，但是官方不考虑，https://github.com/rime/home/issues/1386

我找到了数字后句号和冒号自动转半角的软件内部的代码，这个功能被写死在librime的代码中， 
https://github.com/rime/librime/blob/fe5a65deb1348cd1b45702ded0041029add6dadd/src/rime/gear/punctuator.cc#LL75C1-L75C1

我不确定能否用 lua 实现，因为我对 lua 一窍不通，重申一下，您感兴趣可以考虑一下，不感兴趣您可以直接忽略，您现在的库已经帮助我很多了，再次感谢您的贡献

ps：这个功能我是在 obsidian 软件的 easy typing 插件里见到的，我觉得十分有用，我想把它移植到所有软件，之前我用 ahk 勉强实现了一半这个功能，转到 rime 发现 ahk 获取不了 rime 的中英状态了所以用 ahk 实现不了了，我发现 rime 有 lua 插件，或可能实现，但是 lua 我是真的一点都不了解

_Originally posted by @calmwaves111 in https://github.com/boomker/rime-fast-xhup/issues/9#issuecomment-1750002414_

**Comment by doit132** [comment]
想要使用  AHK  获得 rime 的输入法状态, 可以考虑使用 https://github.com/k-ayaki/IMEv2.ahk/blob/master/IMEv2.ahk 的 IME_GetConvMode 函数

**Comment by boomker** [comment]
@calmwaves111 @doit132 
最近方案加了一个 `;` 前缀输入标点符号的功能， 可以在解决数字后面英文半角`.`和`:` 的问题。属于输入符号的一种替代方式
具体`;` 前缀引导的标点符号规则在 [symbols.custom.yaml](https://github.com/boomker/rime-fast-xhup/blob/84e5314dfd70a3286587164233a9576d8d188ee4/symbols.custom.yaml)  文件里，可自行更改
