### ISSUE TITLE
在其他 rime 配方案中加入 “成对符号，光标居中”功能

### ISSUE THREAD

**Issue by jinghu-moon** [boomker/rime-fast-xhup#16]
使用 rime 方案：**雾凇拼音**

想要在雾凇拼音中加入“成对符号，光标居中”功能，看了下作者的代码。没看懂。大佬可以说下怎么实现吗？

**Comment by jinghu-moon** [comment]
刚才使用了作者的配置文件，连续输入单引号，电脑卡死只能重启。我的步骤如下：
1、删除 rime 文件里所有配置文件
2、将下载的 rime-fast-xhup 里所有文件复制到 rime 文件夹里。
3、打开 notepad3，连续输入单引号，电脑卡死。
这是咋回事呢？

**Comment by boomker** [comment]
1. 成对符号，光标居中功能，只支持MacOS系统
2. 理论上，拷贝成对符号的lua脚本，在雾凇方案里引用这个脚本就可以用了
3. 拷贝方案文件死机，可能的原因是，方案还在部署中，需要时间，尤其是默认开启了几个大词典，在每次部署时，挺吃内存的，内存低于8G估计会卡一会儿。等部署完后，会自动释放占用内存。


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jinghu-moon** [comment]
好的。感谢解答。
