### ISSUE TITLE
仅注释了大词库，输入引号或括号时，按单引号'或(后闪屏

### ISSUE THREAD

**Issue by Well-key** [boomker/rime-fast-xhup#18]

**Comment by Well-key** [comment]
![1](https://github.com/boomker/rime-fast-xhup/assets/78063838/41021d1e-8e4e-4702-8f18-8c9497ca83a7)
如上图，win11专业教育版 22H2，版本：22621.2715
感谢确认。

**Comment by boomker** [comment]
有一个功能是：符号配对， 但是目前只有 macOS 支持， window 不支持
我在 lua 脚本里加个判断，应该就不会闪屏的问题了。
