### ISSUE TITLE
自动补全光标居中lua拓展

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#21]
自动补全光标居中lua里面，是否能加入一个功能，在删除左括号的同时也删除右括号，删除右括号不会删除左括号，和仓输入法逻辑一样，另外自动补全光标居中输入括号之后，总是有些延迟，如果速度快的话，打出的前两个字母不上屏

**Comment by boomker** [comment]
这个功能其实通过 lua 扩展来实现是不容易，这个得输入法前端实现更合适更容易。仓输入法有这个功能也是它的前端实现
配对符号有延迟，这个就是用 lua 扩展实现的尴尬和不合适的体现，目前没法优化性能，如果有， 请提 PR。
