### ISSUE TITLE
无法恢复默认的引号输入方式

### ISSUE THREAD

**Issue by EdwardJunyan** [boomker/rime-fast-xhup#22]
希望能在英文状态下直接输出`直单/双引号`，即`'`、`"`
中文状态下直接输出`弯单/双引号`，即`‘’`、`“”`

即不交换单双引号按键，且能输出直单/双引号

README提到：
```
如果希望恢复默认的引号输入方式，可以在 flypy_xhfast.custom.yaml 里设置“恢复默认引号”。
```
在`flypy_xhfast.custom.yaml`中未找到相关配置。

在`flypy_xhfast.schema.yaml`中将以下两行配置注释后也未生效
```
    '"': {pair: ['‘', '’']}      ## 添加注释后：恢复默认引号
    "'": {pair: ['“', '”']}      ## 添加注释后：恢复默认引号
```
尝试修改`default.yaml`也未成功，可以提供一些思路吗？十分感谢。

**Comment by boomker** [comment]
将这个文件的[这行](https://github.com/boomker/rime-fast-xhup/blob/2f027527304f797bdfaee3cb694dd72715dfcf45/lua/pair_symbols.lua#L32)注释掉，重新部署即可

**Comment by EdwardJunyan** [comment]
感谢，已解决，方案很棒，很适合我这种用不来纯小鹤音形的人😄

**Comment by boomker** [comment]
> 感谢，已解决，方案很棒，很适合我这种用不来纯小鹤音形的人😄

----
这个脚本更新了，现在支持在中英不同状态下输出成对的单双引号了， 可以试试。
