### ISSUE TITLE
如何关闭一些符号模式

### ISSUE THREAD

**Issue by hzinchengdu** [boomker/rime-fast-xhup#24]
如何关闭一些符号模式，比如`/`、`[`和`]` ，现在苦恼怎么关闭。

我的习惯：
- 只用 `[`  `]` 左右方括号来翻页；
- 其他所有符号键都保持不动（英文状态）；
- 所有中文标点用编码打（我有比较完善的自定义词库）；
- 直接辅码引导，不用方括号引导；
- `;` `'` 分号引号二三候选；
- `-` `=` 减号等号以词定字。

![image](https://github.com/boomker/rime-fast-xhup/assets/126546789/2dbc7970-9cc4-47ae-a545-a38250ca7a85)

**Comment by boomker** [comment]
需要改动的文件有多个
1. flypy_xhfast.schema.yaml
* [109行](https://github.com/boomker/rime-fast-xhup/blob/88ff26dbde147aeec538c140ca2ecb0627ebe0ac/flypy_xhfast.schema.yaml#L109) ，删除`[/`等多余符号
* [280行](https://github.com/boomker/rime-fast-xhup/blob/88ff26dbde147aeec538c140ca2ecb0627ebe0ac/flypy_xhfast.schema.yaml#L280) ，删除或注释掉

2. flypy_xhfast.custom.yaml
* [18-19两行](https://github.com/boomker/rime-fast-xhup/blob/88ff26dbde147aeec538c140ca2ecb0627ebe0ac/flypy_xhfast.custom.yaml#L18-L19) , 删除或注释这两行

3. default.yaml
* [173-174两行](https://github.com/boomker/rime-fast-xhup/blob/88ff26dbde147aeec538c140ca2ecb0627ebe0ac/default.yaml#L173-L174)， 解开这两行注释

> 直接辅码引导，不用方括号引导；

目前来说直接用辅码，不用辅码引导符，还是没法在长句输入场景下有满意的体验，原因是程序无法判断是音码还是形码。

**Comment by hzinchengdu** [comment]
谢谢。

`custom_phrase.txt`中的有些“置顶词”并不置顶，怎么解决。
![image](https://github.com/boomker/rime-fast-xhup/assets/126546789/b070c02e-566a-4504-bc06-a969b461ca9a)

**Comment by boomker** [comment]
最后的数字是权重， 数值越大排序越靠前。
第一个是， 嗯
第二个是，嗯(emoji)
第三个是，恩

-------

 `Ctrl+/` 可以临时关闭 emoji ，第二个位置的表情就不会出现了。

**Comment by hzinchengdu** [comment]
明白了，怎么才能固定位置。

**Comment by boomker** [comment]
> 明白了，怎么才能固定位置。

-----

把你期望的候选词的顺序，按照数值权重降序给到，比如
ta    他    3
ta    她    2
ta    它    1

但是这种方式，也有一些问题，貌似会影响自动造词，但是我不怎么用自动造词功能，所以这个可能不是适合所有人。

**Comment by boomker** [comment]
准备写一个词条置顶的 lua， 不影响造词，可自定义词条排序，可快捷置顶和取消置顶。

**Comment by hzinchengdu** [comment]
太好了！我就需要这个功能。置顶词能否有样式区分，比如颜色不一样之类的。

**Comment by hzinchengdu** [comment]
另外希望在readme中补充“Windows系统大词库无法完成部署的问题以及[解决方法](https://github.com/boomker/rime-fast-xhup/issues/23#issuecomment-1999813101)”。

管理员运行那个文件后会弹出两个终端弹窗，等几分钟弹窗消失后就能解决部署问题。

**Comment by boomker** [comment]
> 太好了！我就需要这个功能。置顶词能否有样式区分，比如颜色不一样之类的。

---

可以加上一个标记符号

**Comment by boomker** [comment]
> 另外希望在readme中补充“Windows系统大词库无法完成部署的问题以及[解决方法](https://github.com/boomker/rime-fast-xhup/issues/23#issuecomment-1999813101)”。
> 
> 管理员运行那个文件后会弹出两个终端弹窗，等几分钟弹窗消失后就能解决部署问题。

好的，感谢反馈

**Comment by hzinchengdu** [comment]
“词条置顶的 lua”什么时候能够做好，刚需。

**Comment by boomker** [comment]
> “词条置顶的 lua”什么时候能够做好，刚需。

---

在写了， 目前想办法在解决 bug ，弄好后，发新版本

**Comment by boomker** [comment]
> “词条置顶的 lua”什么时候能够做好，刚需。

----

功能支持了， 你拉取最新项目文件重新部署试试。
按照下面截图的样式来设定 词条置顶， 支持`Ctrl+t` 一键置顶词条

<img width="354" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/b802c6cc-5e03-4ca1-b917-58847539389f">

**Comment by hzinchengdu** [comment]
谢谢开发者！牛逼！
