### ISSUE TITLE
使用小鹤拆分词库

### ISSUE THREAD

**Issue by kip05** [boomker/rime-fast-xhup#25]
https://github.com/mirtlecn/rime-radical-pinyin/tree/flypy

这个分支有转化过的小鹤拆字词库和方案。可以开启用户词典而没有副作用。

```bash
bash rime-install mirtlecn/rime-radical-pinyin@flypy
```

**Comment by boomker** [comment]
好的，感谢，我这就换到这个分支，顺便提个 PR
