### ISSUE TITLE
同文输入法能使用吗

### ISSUE THREAD

**Issue by Z-Vaj** [boomker/rime-fast-xhup#26]
一直使用的是你的方案，特别好用，今天换了安卓手机，准备把输入方案也切换过去的，发现同文输入法好像无法使用，方案复制进去部署软件就会闪退

**Comment by boomker** [comment]
啊这， 我没考虑过用在移动平台上，项目里也没移动平台上的 Rime 配置，所以不能盲目复制方案到安卓上的。
这样吧， 我这几天尝试弄一个适配安卓的配置方案放到项目里吧。

**Comment by ZhuYanQing2** [comment]
大佬，还是安卓闪退的问题，我现在用的方案非常难受，还是想用你这个方案，不知道是什么冲突导致安卓使用不了，如果可以简化方案也OK，比如只要词库和输入时间的lua，不知道删哪些文件和配置代码。

**Comment by boomker** [comment]
实在不好意思， 之前两周在忙项目，没抽出时间来搞安卓，这周我抽点时间来搞一下。
目前不确定安卓版的 Rime 是否支持大词典，可能得取舍一部分词典了。

**Comment by ZhuYanQing2** [comment]
🫰

**Comment by boomker** [comment]
昨天在安卓上用 同文输入法，部署多个方案也总是会崩溃， 感觉是应该是同文输入法的问题，等过段时间我再弄弄看

**Comment by boomker** [comment]
同文不准备折腾了，移动端小企鹅(Fcitx5-Android)  感觉容易上手，好用一点。
