### ISSUE TITLE
快捷指令移动端支持

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#27]
快捷指令可否改变引导符ofk 如何改变 然后 能不能固定顺序

**Comment by boomker** [comment]
引导符可以改的， 目前改代码中的这些位置
<img width="902" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/7fea074e-f98d-46ef-9401-733e0e93cb43">

后面我再弄成可配置的，不用改代码的方式
顺序固定，这个理论上应该可以， 可能有点麻烦，有个可能实现思路， 但是得验证才行

**Comment by Hodwe** [comment]
谢谢，我知道了，这个不能用在ios上吗？这个快捷输入很好用，但是不能同步，作用小了很多

**Comment by boomker** [comment]
我没有 iOS 设备，在移动设备上暂时没有动力去折腾了，看后面有精力了再尝试吧

**Comment by Hodwe** [comment]
谢谢，我认为只需要弄快捷输入，快捷启动就不必了

**Comment by boomker** [comment]
快捷启动， 其实我也用的少， 之前用 PC 上小鹤的时候有这个功能， 就顺便在Rime 上实现了

**Comment by Hodwe** [comment]
着实牛，我尝试用chatgpt改代码，实现iOS可用，完全没啥用，这有打赏渠道么

**Comment by Hodwe** [comment]
谢谢，之前已经点了，快捷启动有用，很好用，主要是快捷输入，大佬有时间可以整一个

**Comment by boomker** [comment]
> 谢谢，之前已经点了，快捷启动有用，很好用，主要是快捷输入，大佬有时间可以整一个

好的， 感谢支持，后续会把功能完善一些，你也可以提出一些好的想法哦

**Comment by Hodwe** [comment]
我的配置都是ios和macos共用的，ios一直显示下面的错误：

```
Lua Compoment of initialize  error:( module: launcher_processor name_space: launcher_processor status: 2 ): ...2-436A-A4C6-C40ACB880A26/Documents/Rime/lua/launcher.lua:25: 'popen' not supported

Lua Compoment of initialize  error:( module: launcher_translator name_space: launcher_translator status: 2 ): ...2-436A-A4C6-C40ACB880A26/Documents/Rime/lua/launcher.lua:25: 'popen' not supported
```

**Comment by boomker** [comment]
已经更新了， 你再拉下更新试试

**Comment by Hodwe** [comment]
太棒了，已经用上了，整体不错，有几个想法：
刚需：
1. 上面所说的只在ios出现的错误，希望能得到修复
```
Lua Compoment of initialize  error:( module: launcher_processor name_space: launcher_processor status: 2 ): ...2-436A-A4C6-C40ACB880A26/Documents/Rime/lua/launcher.lua:25: 'popen' not supported

Lua Compoment of initialize  error:( module: launcher_translator name_space: launcher_translator status: 2 ): ...2-436A-A4C6-C40ACB880A26/Documents/Rime/lua/launcher.lua:25: 'popen' not supported
```
2. 在ios上没办法通过手指点击候选项选词，必须通过空格，这一点在ios上非常不方便，希望能够优化
3. 固定ofk的词序
不太刚需：
1. 上次说的添加一个修改ofk修饰词的地方
2. 输入ofk时没办法直接通过enter输出字母ofk
3. ofk中的类似命令的终端这些在iOS中做不到的可以屏蔽
谢谢

**Comment by Hodwe** [comment]
1. 现在ios上没有报错了，谢谢
2. 这一点在ios上真的是刚需中的刚需，如果没办法点击，移动候选项都是一件难事，大佬看看有没有其他的方法能够实现，不能实现的话用起来真的很费劲，其他的都是小事

**Comment by boomker** [comment]
其他方式实现，这个对我有点困难了，我对 Rime 和 iOS 开发这块儿没有经验诶，难以搞定。可以在 `librime`   和 `librime-lua` 项目提 issue， 支持移动平台的触控事件

**Comment by Hodwe** [comment]
librime 提供按序号而非空格或数字键选词的 API
https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime_api.h#L299-L300
所以问题不在librime，看看librime-lua那边怎么解决

应该得再等等

**Comment by Hodwe** [comment]
library lua已经回复了，这样是不是就没办法了，我也不懂怎么说

librime-lua作为librime的扩展，只处理日志逻辑，你说的点击是前端的事情

**Comment by boomker** [comment]
我回复了， 应该是 librime-lua要做支持的

**Comment by Hodwe** [comment]
谢谢

**Comment by mokapsing** [comment]
已经有select(index)了，可是你该怎么和前端点击挂钩呢？ @Hodwe @boomker

**Comment by mokapsing** [comment]
我认为是仓输入法前端点击事件要调用 https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime_api.h#L299-L300
而不是纠结lua有没有导出这两个接口

**Comment by mokapsing** [comment]
仓输入法作者回应仓输入法是支持点击选择的
![image](https://github.com/boomker/rime-fast-xhup/assets/39441028/7d2513f2-7079-47ba-9967-a28b4257f591)

**Comment by Hodwe** [comment]
刚问了付佬，这样回复
![IMG_0765](https://github.com/boomker/rime-fast-xhup/assets/158744320/ea0f54ba-220a-47f3-9bab-0e0736029f39)

**Comment by boomker** [comment]
Rime 引擎内部如果不支持捕获到点选操作的事件，那应该是没法在 Lua 脚本里支持触控点选候选项的

**Comment by mokapsing** [comment]
> > 一个后端引擎怎么会去捕获界面的事件呢？
> 
> 我的意思是说，前端得把点选事件传递给后端做处理，后端得有接口分辨出接收到的是点选操作，而不是按键

如你所知，后端目前有[支持点选的接口](https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime_api.h#L299-L300)，但是并不关心点击事件本身

**Comment by boomker** [comment]
好吧，目前脚本是通过用户按键来判断下一步是 `进入菜单` 还是 `上屏候选项`，后面试着改改，选中候选项来判断下一步操作

**Comment by Hodwe** [comment]
谢谢，我也问了hamster作者，看了其他作者的配置，实在不能实现也没事，可以尝试固定候选项，然后通过数字选择也可以，辛苦

**Comment by boomker** [comment]
> 可以尝试固定候选项，然后通过数字选择也可以

---
目前已经实现了， 不过需要在指令名称后面加上数字序号，不然没法按序固定候选项
<img width="318" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/ec094cf0-90e0-499b-bb52-96a662e55776">

**Comment by Anber55** [comment]
已经用上了
另外，像邮箱、卡号、书签这些前面的mb、cn、bm有什么用能去掉吗？我输入ofk，再输入bm好像没办法出来书签，如果输入ofk之后再输入1-2个字母就能出现下一级，对ios也挺好的
还有，能不能直接在launcher_config.lua添加新的项目，例如复制tc终端命令，重新整一个其他的

**Comment by Hodwe** [comment]
在用了，谢谢
触发词好像有些问题，刚才将触发词改为
local appLaunchPrefix = "uu"
local favorCmdPrefix = "u"
无法触发成功
更改为符号;也无法触发成功

**Comment by boomker** [comment]
>
local appLaunchPrefix = "uu"
local favorCmdPrefix = "u"

----
这两个字符确定不会和正常打字相冲突吗。
最好改成不与正常打字输入码相冲突的触发前缀，即非双拼或全拼的编码，或叫空码，比如`uU`，`oi`

**Comment by Hodwe** [comment]
支持符号吗
还有像卡号前面的cn能删除吗？我输入ofk，再输入cn不能到达卡号这里
另一个疑问就是bm书签我能直接复制做成另外一个类型吗，例如：
		["wz网址"] = {
			["action"] = "open",
			["items"] = {
				"https://youtube.com",
				"https://bilibili.com",
				"https://github.com",
			},
		},

**Comment by boomker** [comment]
> 还有像卡号前面的cn能删除吗？我输入ofk，再输入cn不能到达卡号这里

可以删除的， 输入`ofk` --> `c` ，可以进入「卡号」二级菜单
可以自行添加一级菜单及包含的二级菜单内容

> 支持符号吗？
你是说触发前缀用 符号，是吧？
这个应该也可以，我测试一下，之前没考虑过。

**Comment by boomker** [comment]
> 支持符号吗

简单尝试了一下，用符号来作为触发前缀，不是一个很好的实践，还是用特定的字母字符吧

**Comment by Hodwe** [comment]
好的，谢谢，ofk后面加的c在哪儿定义呢，就是【cn卡号】前面的c吗？还是得在其他地方设置

**Comment by boomker** [comment]
> 就是【cn卡号】前面的c吗？

对的

**Comment by Hodwe** [comment]
我的launcher.lua是直接搬过来的，launcher_config.lua做了自定义改动，目前固定顺序好像不起作用

<img width="242" alt="截屏2024-04-12 14 21 45" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/9c21e495-34eb-4f68-9e5f-0e5343549ac0">

**Comment by boomker** [comment]
还要加其他配置才行
1. `rime.lua` 里加上[这句](https://github.com/boomker/rime-fast-xhup/blob/54a80d8635cb0825cf47f701cca0d1e79fb9f5c2/rime.lua#L148)
2. `flypy_xhfast.schema.yaml` 里加上[这句](https://github.com/boomker/rime-fast-xhup/blob/54a80d8635cb0825cf47f701cca0d1e79fb9f5c2/flypy_xhfast.schema.yaml#L101)

**Comment by Hodwe** [comment]
全部加了，但是变的很奇怪，看下图，快捷启动的选项没有置顶，而且按=到下一页按不动，输入数字或空格会导致直接上屏，
然后如果输入完触发词，再输入c，还是可以进入卡号，照常输出

<img width="212" alt="截屏2024-04-12 14 58 14" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/b9627b67-af46-4d4f-86f9-54fda1a47ef8">

**Comment by boomker** [comment]
更新一版，你拉取最新项目文件试试。
一级菜单没有固序输出的情况，这个得看你的配置了。我这边时正常的
<img width="283" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/13b3c25a-37d8-4a8d-8e0b-4f84beb785ac">

**Comment by Hodwe** [comment]
我可能找到原因了，如果我不改触发词，在上个版本是完全正常的，新版本还是置底的问题
改了触发词就问题很多

**Comment by boomker** [comment]
触发前缀最好用空码，即不对应任何汉字和英文的编码
比如`uU`
<img width="257" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/3b9af16d-88b3-4fae-837d-69e4a1b2f325">

**Comment by Hodwe** [comment]
我是全拼，之前用的ofk就不是空码，所以我觉得问题是在【改变触发词】导致的问题，我现在在外面，回去我再改成空码测试一下

**Comment by boomker** [comment]
我大概知道你可能遇到的错误情况了，开启了超级简拼应该会出现这种情况。稍等会再出一版，应该就好了。

**Comment by Hodwe** [comment]
好了，完美，谢谢，用符号也可以上个版本符号置顶了，最新版本置底了

**Comment by Hodwe** [comment]
现在已经很好了，目前的需求就是：
1. ios上一行的空间本来就小，能不能保留mac每个选项后面的〔快捷指令〕，ios设置一个选项，可以自己选择是否隐藏
2. 除了住选项可以排序，打开之后的每个小选项能不能排序，因为不能排序太杂乱了，排序了也方便记忆，例如：cn卡号点开之后，固定身份证排第一个，招商银行排第二，其他也是

**Comment by Hodwe** [comment]
佬，看到更新了，试了一下，又出现了之前显示不全、交错在一起的问题（二级菜单也显示不全）

**Comment by Hodwe** [comment]
不小心关了，补一张图片
![IMG_0835](https://github.com/boomker/rime-fast-xhup/assets/158744320/9c413675-32d8-4fa1-a05d-795cd2349137)

**Comment by boomker** [comment]
> 又出现了之前显示不全、交错在一起的问题（二级菜单也显示不全）

是电脑端还是移动端？ 有截图吗？
二级菜单固序， 也要像之前一级菜单一样， 在配置文件里给菜单名称末尾加上数字序号的

<img width="190" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/e9122a15-7ba6-4fb6-8550-e7d09d019ca4">

<img width="192" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/d39a46c9-3579-48b8-9176-36dbf984a4ba">

<img width="231" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/7054029b-56e3-4ae7-862f-333fda3fb482">

我这边没有出现显示不全的情况

**Comment by Anber55** [comment]
是ios。我一会再试试，是这么添加的吗

<img width="378" alt="截屏2024-04-15 10 15 39" src="https://github.com/boomker/rime-fast-xhup/assets/117334130/adfade1b-3406-4f5c-b19d-cdc1d531b18d">

**Comment by boomker** [comment]
@Anber55 
对的。 
我知道 @Hodwe 你说的问题是啥了，稍等，更新一版

**Comment by Hodwe** [comment]
好的，我现在试试，确认一下，二级菜单的固定顺序：
如果是下面的形式，就在[]内的末尾添加序号是吧
["联通1"] = "10000000000",
["联通2"] = "11111111111",
如果是下面的形式，就在""内的末尾添加序号是吧
		["m邮箱1"] = {
			["action"] = "commit",
			["items"] = {
				"a@gmail.com1",
				"c@qq.com2",

**Comment by boomker** [comment]
> ["m邮箱1"] = {
["action"] = "commit",
["items"] = {
"a@gmail.com1",
"c@qq.com2",

---
邮箱这种应该是会按照默认你配置文件里的顺序的，不用写序号的

**Comment by Hodwe** [comment]
问题反馈：
1、我的联通号码有2个，原本设置的是：
联通1
联通2
现在改为
联通11
联通22
移动3
电信4
显示有点混乱
2、书签像下面设置不生效，最终展示的结果会带上后面的数字，没有排序
		["b书签5"] = {
			["action"] = "open",
			["items"] = {
				["C1"] = "https://co",
				["画图2"] = "https://jspaint.app/",
				["MacApp3"] = "https://macaorg.cn/app/",
				["Macked4"] = "https://m.app/",
				["remove5"] = "https://www.ree.bg/zh",
				["rime-fast-xhup6"] = "https://github.com/boomker/rime-fast-xhup",
			},
		},
3、路径的问题同上：
		["f路径6"] = {
			["action"] = "open",
			["items"] = {
				["Rime用户1"] = "~/Library/Rime",
				["Rime安装2"] = "/Library/Input Methods/Squirrel.app/Contents/SharedSupport",
				["微信备份3"] = "~/Documents",
			},
		},
4、终端的问题也是和上面一样
图片：
<img width="151" alt="截屏2024-04-15 11 54 46" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/d901d5d7-3183-4f80-b654-460ce4042dff">

**Comment by boomker** [comment]
@Hodwe 
你拉取的是最新的项目文件代码吗
有一点要注意， 菜单名称不能是全字母的，得有中文，不然没法识别是自定义候选项还是输入法程序处理出来候选项

> 联通11 联通22

保持之前的
联通1
联通2
没啥问题吧

**Comment by Hodwe** [comment]
之前的launcher.lua没问题，现在的launcher.lua用了之后一直出现下面这种情况
折腾半天没弄好，如果我需要用超级简拼，哪里的设置需要注意
<img width="117" alt="截屏2024-04-15 13 26 06" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/a61fe6af-11ac-44a9-b2f3-5a27e3896bba">

**Comment by Hodwe** [comment]
这是我的部分名称的设置
<img width="85" alt="截屏2024-04-15 13 32 33" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/648aafa2-522e-4b04-9c95-3a2b00affce9">
<img width="95" alt="截屏2024-04-15 13 32 42" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/a27a2f03-c006-48bb-b915-39062474ad8c">
<img width="110" alt="截屏2024-04-15 13 33 02" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/bf9bde60-48a9-4338-a8b3-27a107730c82">
<img width="108" alt="截屏2024-04-15 13 33 09" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/8e497b47-7e26-4e3d-9b2a-d9cc3bd69e9a">
<img width="135" alt="截屏2024-04-15 13 33 27" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/1e833613-4777-4b91-997c-74d763e7f290">

**Comment by boomker** [comment]
有截图吗？
另外 要把[这行](https://github.com/boomker/rime-fast-xhup/blob/050bf8db2986522e5a854d7fe3ee998f6063b4e4/flypy_xhfast.schema.yaml#L110)放到 `Filter`  下面

**Comment by Hodwe** [comment]
之前已经放了，需要哪部分的截图~

**Comment by Hodwe** [comment]
我刚才试了一下，用你的launcher.lua和launcher_config.lua也会出现下面这种一模一样的情况
<img width="117" alt="截屏2024-04-15 13 26 06" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/5277a2e2-7b65-453a-bb96-803f58fb6554">

**Comment by boomker** [comment]
> 我刚才试了一下，用你的launcher.lua和launcher_config.lua也会出现下面这种一模一样的情况 <img alt="截屏2024-04-15 13 26 06" width="117" src="https://private-user-images.githubusercontent.com/158744320/322369643-5277a2e2-7b65-453a-bb96-803f58fb6554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjM4MjksIm5iZiI6MTcxMzE2MzUyOSwicGF0aCI6Ii8xNTg3NDQzMjAvMzIyMzY5NjQzLTUyNzdhMmUyLTdiNjUtNDUzYS1iYjk2LTgwM2Y1OGZiNjU1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNjQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2E4NDAwMDEyNGVjM2RlNjFlNDExZDYzYjZkNTNlMTc1YzQzZjIxZTYyNmJkOTU5Y2FiNGVjYzY0MmQyYTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nlovbE526HVa59KObFwtE75z-_0rFjhAEqEciGSTH2E">

---

你的意思是，不出现一级菜单是吗？ 还是啥
要把[这行](https://github.com/boomker/rime-fast-xhup/blob/050bf8db2986522e5a854d7fe3ee998f6063b4e4/flypy_xhfast.schema.yaml#L110)放到 Filter 倒数第二行，这一步操作了吗？

**Comment by Hodwe** [comment]
不好意思，刚看到，这一步之前早就放了，出现的问题就是一级菜单不显示，直接照搬你的launcher.lua和launcher_config.lua也不行，输入u之后，只显示【u〔快捷指令〕】，然后输入二级菜单时，只有um会显示邮箱，可能是因为um在launcher_config.lua中的设置和其他的不一样，而且um第一次会显示邮箱，第二次输入就不会了，除非重新部署

**Comment by boomker** [comment]
应该是触发前缀得要是一个特殊的，最好是不对应任何汉字和英文编码的字符。你尝试换成其他的，比如`ak`。

**Comment by Hodwe** [comment]
佬，我是全拼，设置的触发词改成了iu，是空码，但是还是一样的情况，不仅仅是一级菜单不显示，二级菜单也基本不显示
<img width="128" alt="截屏2024-04-16 06 45 52" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/31406bff-66dd-44ee-b623-bde1cb253e20">

**Comment by boomker** [comment]
输入触发词后，没有任何候选项吗？如果你开启了超级简拼， 输入`iu`应该也会有其他汉字的候选项的吧
你这样， 把那个`filter` 放到顶部试试， 感觉应该是和其他`filter` 冲突了。
或者， 你把其他`filter` 都注释掉，只开`launcher` 的滤镜(filter 功能)

**Comment by Hodwe** [comment]
在全拼里面，iu是空码，而且我刚才将触发词设置为了uiui，把其他的filter内的lua全删了还是不行，还是那种情况

**Comment by boomker** [comment]
你把配置打包发我看下， 词库文件不需要包含了

**Comment by Hodwe** [comment]
[2024.04.16-14.46.35.zip](https://github.com/boomker/rime-fast-xhup/files/14987931/2024.04.16-14.46.35.zip)

**Comment by boomker** [comment]
我这边用你的配置，没有问题
<img width="159" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/d74dcb22-0961-47d8-a4fd-8b53b841507d">

<img width="198" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/9abf9e74-6b27-48e4-9aa0-9616014449e6">

<img width="137" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/bc66f4a7-5c7c-4bdd-93a5-35b44e9c2d07">

**Comment by Hodwe** [comment]
好奇怪，什么都没改吗？我这是怎么了，同一个配置我这不行

**Comment by boomker** [comment]
> 好奇怪，什么都没改吗？我这是怎么了，同一个配置我这不行


不加词库和加词库，都试过了， 其他修改没有， 测试下来没有问题，
你看下 你输入法程序的版本 ，还有 librime 版本

**Comment by Hodwe** [comment]
我用的就是鼠须管的0.16.2，librime 版本不知道

**Comment by boomker** [comment]
> 我用的就是鼠须管的0.16.2，librime 版本不知道

https://github.com/rime/librime/releases/tag/1.11.0

<img width="390" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/97e6114f-6171-445e-8d53-fc23edd1d623">

**Comment by Hodwe** [comment]
佬，没有单独安装过这种Library，这个利用终端怎么安装~

**Comment by boomker** [comment]
> 佬，没有单独安装过这种Library，这个利用终端怎么安装~


放到下图的位置：
<img width="988" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/a97ef62d-9043-4e08-bf62-c50e00887290">

**Comment by Hodwe** [comment]
佬，没太明白，这一块完全小白，是把整个压缩文件还是里面的某个文件进行放置，具体放到哪个文件夹呢

**Comment by boomker** [comment]
> 佬，没太明白，这一块完全小白，是把整个压缩文件还是里面的某个文件进行放置，具体放到哪个文件夹呢


当然要解压缩包，把文件放到对应的位置

**Comment by Hodwe** [comment]
谢谢，最终确认一下，是把下图中的【3个文件和2个文件夹】全部放到
/Library/Input Methods/Squirrel.app/Contents/Frameworks/这个文件夹下面是吗？

<img width="493" alt="截屏2024-04-17 07 56 56" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/138ba210-caf4-4dbe-a3d4-bd691c841bf0">

<img width="182" alt="截屏2024-04-17 07 55 00" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/2c23ca07-d56d-46de-84b0-216d7c0d88f7">

**Comment by boomker** [comment]
> 下图中的【3个文件和2个文件夹】全部放到
/Library/Input Methods/Squirrel.app/Contents/Frameworks/这个文件夹下面是吗？

是的
有一点要注意，你 macOS 版本 低于13的话，可能会有不兼容的情况

**Comment by Hodwe** [comment]
已经都放进去了，需要其他方式激活吗？或者怎么检测是否成功，我的mac系统是13.6
<img width="736" alt="截屏2024-04-17 11 10 53" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/70ce387a-d6d4-4c06-b5f8-dba6dd22a3ed">

**Comment by boomker** [comment]
> 需要其他方式激活吗？

不需要，重新部署即可

**Comment by Hodwe** [comment]
上面的操作都成功了，但是好像Library没有升级，我用你的方案，输入ofk仍然是不行，不知道问题出在哪儿

https://github.com/boomker/rime-fast-xhup/assets/158744320/e0cc0ef8-38e3-4844-9a6a-5cd1fff9179c

**Comment by boomker** [comment]
那就不知道了，只能这样了，把这个  `/Library/Rime`，重命名后，把我的配置重新拉下来部署试试
我现在把触发前缀都改成 `/`开头了。
<img width="183" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/84895890-d6e2-477c-af59-e5c501ad0f5e">

**Comment by Hodwe** [comment]
重启之后就可以了，你有没有这种情况，改为/之后，通过字母选对应选项好像没法选择


https://github.com/boomker/rime-fast-xhup/assets/158744320/84460dd8-4e6d-4dae-bf30-4e1386c404d2

**Comment by boomker** [comment]
触发前缀不能和已有程序自带的重合，否则会有冲突的。
单个`/` 触发前缀是 Rime 只带的， 比如这种：
<img width="114" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/613f92de-ede5-428c-8727-76cd8eb9c6b7">

**Comment by Hodwe** [comment]
没有冲突，这些地方我都改成其他符号了，alphabet中也设置了，就差patterns没有设置

**Comment by Hodwe** [comment]
顺便问一下，这里的3个字符集分别代表的是什么字符，我目前用的是下面这个，很久没更新了，不知道还准确不
  - options: [standard, big5, gbk, utf8] #生僻字过滤，依次词库变大
    reset: 3
    states:
      - 规范
      - BIG5
      - GBK
      - UTF8


  - options: ["utf8", "gbk", "gb2312"]    # 字符集选单
    reset: 0                              # 默认 UTF8
    states:
      - UTF-8
      - GBK
      - GB2312

**Comment by boomker** [comment]
> 这里的3个字符集分别代表的是什么

简单来说，分别代表不同的字符编码标准，` UTF8`字符集包含可输出的字符最多，同时可能也会出现一些无法显示的字符(取决于字体支持)，其他字符集一般不会包含很多生僻字，以简体为主。
如果你不想看到生僻字或无法显示的字，就选用 `GBK`

**Comment by Hodwe** [comment]
好的，谢谢，我安装了第三方字体，可以显示陌生字符，那我用你这个吧，这三个字符集应该是按照字符集从大到小的顺序排序的吧
UTF-8
GBK
GB2312

**Comment by boomker** [comment]
现在二级菜单也可以通过给 *菜单名称*加首字母来快捷触发了，修复了一些 bug， 应该比之前更好用了。
@Hodwe
