### ISSUE TITLE
我现在打字时不时出现繁体字，不知道为什么

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#28]
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/13d6dacb-2d2f-410b-9e6e-5a09a9f897c6)

![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/e3394a7a-21d0-418e-a0b6-ea573e17acbc)

用的是最新的库，win10，因为词典太大了，所以我用的这个办法来部署的词库，不清楚是否与此有关，一个月前没有繁体的问题，是最近这几次更新才有的

https://github.com/boomker/rime-fast-xhup/issues/23#issuecomment-1999813101

**Comment by boomker** [comment]
你先试试，按下`Ctrl+0`，切换简繁。

**Comment by calmwaves111** [comment]
> 你先试试，按下`Ctrl+0`，切换简繁。

没有用，是简体

![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/151f6afa-b91f-4b79-9f72-d5829e89afec)

[rimedeployerx64.zip](https://github.com/rime/weasel/files/12496136/rimedeployerx64.zip)
用这个部署大词库的时候会有一些log，但是它部署完就关闭黑窗了，我截了一下，会有这种报错，不确定是否与此有关
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/6c832b5d-1e33-426c-b13f-43f582de9c84)

主要是win10 x64 部署不了大词库，就很烦

**Comment by boomker** [comment]
跟这个报错应该没有关系的。
检查部署目录的文件和最新的项目文件是否有差异， 最新的项目文件 变更了 OpenCC相关的文件和配置，可能和这个有关系

**Comment by calmwaves111** [comment]
很神奇，似乎我把flypy_xhfast.userdb文件夹删掉就可以了，我折腾了好久，又是把小狼毫卸载了几遍，又是删掉整个 Rime 文件夹

现在对最新的库，我有两个问题，一个是唯一码直接上屏似乎没了，以前我打成语之类的会直接上屏，另一个是如果我打全码，反而没有任何待选项

比如  ddxrxl 待选项
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/34ffb637-85be-45df-856b-eb653e4a2213)

**Comment by boomker** [comment]
把[这行](https://github.com/boomker/rime-fast-xhup/blob/e63c5ef175a43dd5166a1a549fdfcc507f83f5fa/flypy_xhfast.schema.yaml#L16)解开注释，重新部署试试。
成语自动上屏， 这个默认是关闭的，因为可能其他人不喜欢， 默认关闭的话，可能会 打全码会不出字

**Comment by calmwaves111** [comment]
好嘞我又可以了（这两天折腾这个都快放弃回搜狗了

感谢大大一直维护，耐心解答🙏
