### ISSUE TITLE
pair_symbols 光标居中性能问题

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#29]
1. pair_symbols.lua对于mac来说很好用，但是会导致ios出现问题，如果ios添加了下面这2行

	["apostrophe"] = { "“”", '""' },
	["quotedbl"] = { "‘’", "''" },
输引号时就会出现这样的情况
‘’“
“”‘
mac都是正常的，看能否针对ios修复
2. 很多lua上面有
-- local puts = require("tools/debugtool")
tools/debugtool是必须放在lua是吗

**Comment by boomker** [comment]
1. 更新了一版，拉一下最新项目，重新部署试试
2. 这个不是必须的， 只是在我调试代码的时候加上的，已经注释了，不会在代码里起作用

**Comment by Hodwe** [comment]
1. lua内的单引号和双引号应该是故意设置反的，如果在ios按设置的打符号，出现的是下面这样：
	["apostrophe"] = { "“”", '""' },
	["quotedbl"] = { "‘’", "''" },
“”‘
‘’“
'‘’“'
"'‘’“'"

2. 如果将上述单引号和双引号设置正确，如下，打出来的是：
	["apostrophe"] = { "‘’", "''" },
	["quotedbl"] = { "“”", '""' },
“”“
‘’‘
'‘’‘'
"'‘’‘'"

ios的问题没有得到更正
原因我试过了，关键就在：
	["apostrophe"] = { "“”", '""' },
	["quotedbl"] = { "‘’", "''" },
如果把它删掉，ios立马就正常了，但是删掉之后，mac又不行了，大佬看看怎么改

**Comment by boomker** [comment]
iOS 上不生效，可能是 iOS 系统不允许脚本做系统调用的操作，是系统安全机制阻挡了，在最新的 macOS 上也有类似的情况，目前没有办法解决。

---

> 如果把它删掉，ios立马就正常了，但是删掉之后，mac又不行了

能否录屏看下， 不清楚你操作的环境，删掉之后，  Mac 应该不会有影响的

**Comment by Hodwe** [comment]
ios：
https://github.com/boomker/rime-fast-xhup/assets/158744320/306af092-22c2-487a-8a7b-89193795b0b6

mac存在（有一个其他问题，见视频）：
https://github.com/boomker/rime-fast-xhup/assets/158744320/22ffbeee-ca8f-4212-8579-ca28cbf2c8c3

mac不存在：
https://github.com/boomker/rime-fast-xhup/assets/158744320/54982d8c-c615-445f-a7bb-dcdd2ee29f06

**Comment by boomker** [comment]
这个脚本又更新了一版，你放到 iOS 上再试试。
`quotedbl`, `apostrophe`, 现在这两个键在 iOS 上会忽略掉，不会起作用
Mac 上的问题， 这个应该不太好解决， 让光标居中，是通过`osascript`来调用系统 API 实现的， 会有这种问题， 除非用其他方法来实现，目前还没想到更好的实现方式， 那位大佬有，请提一个 PR。

**Comment by Hodwe** [comment]
现在ios正常了，其实现在只有一个问题了
就是mac的单引号都正常，但是到双引号时，就会出现以下问题
就是输入中英文双引号，右半边显示蓝色，输入字符都会将右半边符号覆盖
https://github.com/boomker/rime-fast-xhup/assets/158744320/4f08e9f8-d60c-4def-9859-d524c40dcc1e

**Comment by Hodwe** [comment]
另外，只有引号会这样，其他符号暂时正常

**Comment by boomker** [comment]
> 就是输入中英文双引号，右半边显示蓝色，输入字符都会将右半边符号覆盖

---
这个主要还是光标居中的操作来不及，性能不好导致的，后面想办法专门写一个光标居中的程序试试看了。

**Comment by Hodwe** [comment]
bug反馈，拉取了最新更新后，pair_symbols.lua虽然没有更新，但是出了一些问题，只能成对符号，不能光标居中

**Comment by Hodwe** [comment]
我用你的方案名试了一下，也不行

**Comment by boomker** [comment]
> 我用你的方案名试了一下，也不行

这个我也不知道咋解决，我这边也是不能光标居中了。
之前旧版的 MacOS 还能居中的，升级系统之后就不行了，感觉应该是系统对于应用程序模拟按键操作有限制了。

**Comment by boomker** [comment]
找到问题了

<img width="715" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/5635f407-5db1-43d8-b2b5-7d9202cc46e5">

选中`Squirrel`，点击下面的「-」删除， 重新添加一遍即可恢复正常
路径为：/Library/InputMethods/Squirrel.app

**Comment by Hodwe** [comment]
好了，感谢

**Comment by huangkengwei** [comment]
> 现在ios正常了，其实现在只有一个问题了 就是mac的单引号都正常，但是到双引号时，就会出现以下问题 就是输入中英文双引号，右半边显示蓝色，输入字符都会将右半边符号覆盖 https://github.com/boomker/rime-fast-xhup/assets/158744320/4f08e9f8-d60c-4def-9859-d524c40dcc1e

有一种可能是，shift键松开时间晚了，导致“shift + ←”变成选中快捷键。

**Comment by boomker** [comment]
> 有一种可能是，shift键松开时间晚了，导致“shift + ←”变成选中快捷键。

是的，这种情况就比较麻烦， 移动光标时看是否可以忽略` shift`键了。

**Comment by Anber55** [comment]
请问换成哪个小工具了，需要我下载吗

**Comment by boomker** [comment]
> 请问换成哪个小工具了，需要我下载吗

在项目方案里，不用下载
