### ISSUE TITLE
在windwos 11 部署不成功

### ISSUE THREAD

**Issue by zigeweiwu** [boomker/rime-fast-xhup#3]
第一次部署没有error信息
第二次才有如下：
![image](https://github.com/boomker/rime-fast-xhup/assets/95293685/b3103752-bbf6-48ac-a45d-7ee7e88a74b3)

**Comment by boomker** [comment]
你看看你那边是否影响正常输入, 然后看下小狼毫用的是那个版本, 最好是把 librime-lua 升级到最新哦
由于我没在 Windows 上测试过, 你截图的那种报错我没遇到过.

**Comment by BigOldTree** [comment]
中文不能输入，我再去除一些功能试试

**Comment by BigOldTree** [comment]
window 11  部署成功了 , 配置文件中有两处需要修改:
1. 拆字字配置错了

![image](https://github.com/boomker/rime-fast-xhup/assets/95293685/8e869b54-5182-4acc-8b44-c7b43159f2a7)
![image](https://github.com/boomker/rime-fast-xhup/assets/95293685/61a29d5b-651b-44f4-ae3d-4a3d2994c6ce)


2. 词库配置中配置了一个没有词库的配置文件(可能是下载时超市没有下载下来)
![image](https://github.com/boomker/rime-fast-xhup/assets/95293685/670ad521-8e3f-4e0f-a7cd-33959e0ee2d0)
![image](https://github.com/boomker/rime-fast-xhup/assets/95293685/8471a072-9a9a-49a1-a047-622f7f918c22)
