### ISSUE TITLE
音形码引导问题

### ISSUE THREAD

**Issue by Z-Vaj** [boomker/rime-fast-xhup#30]
speller/algebra/@next: derive/[[]//
大佬，我配置里面打开了这个设置，但是我打单字直接引导的时候，出来的都是词组，还是必须按］键才能引导，请问下大佬是不是词库的问题，这个情况要怎么才会优先出我引导的字，而不是词组，谢谢！

**Comment by ZhuYanQing2** [comment]
![image](https://github.com/boomker/rime-fast-xhup/assets/32755771/c930abdc-d997-4a17-80c5-e335568d8c2c)
大佬看下缩进是否有问题

**Comment by boomker** [comment]
放到 `flypy_xhfast.custom.yaml`文件最后一行，注意缩进

**Comment by Z-Vaj** [comment]
解决了，非常感谢！现在就差安卓的了😁

**Comment by boomker** [comment]
安卓平台上 Trim 之前尝试用了一下，感觉有 Bug。 后面看有稳定版本了， 再尝试整整
