### ISSUE TITLE
快捷键问题

### ISSUE THREAD

**Issue by rwerplus** [boomker/rime-fast-xhup#32]
编码反查功能如何修改为`，之前修改完不生效；
翻页功能如何变为 Backspace 键 前面的加号和减号

**Comment by boomker** [comment]
1. 需要把字库里注音中的`[`，转换为`。 最新项目配置已经支持了
2.   - {when: paging, accept: BackSpace, send: Page_Up}

**Comment by rwerplus** [comment]
感谢，我试试
