### ISSUE TITLE
[Bug] 在某些情况下, 行首输入英文时, 会自动在前面添加空格

### ISSUE THREAD

**Issue by doit132** [boomker/rime-fast-xhup#34]
输入英文自动添加空格, 应该是中英混合输入的功能, 这个功能挺好的, 但是使用过程中发现有一些问题, 比如在 vscode 的搜索框中输入英文会在前面自动添加空格 (这会影响搜索, 不得不将光标移动到开头删除空格)

![image](https://github.com/boomker/rime-fast-xhup/assets/117004316/6299fce8-229b-4c82-8f19-fa477ef890a2)

视频演示: 

在中文模式下输入 hha,  然后 enter,  会发现在输入框最开头处增加了一个空格

![recording](https://github.com/boomker/rime-fast-xhup/assets/117004316/b227e9b9-6e73-4edf-a055-536733d2cb5d)

**Comment by boomker** [comment]
空了，我改改，这个功能其实很难做到完美。
用户从一个应用切换另一个的时候， 程序没法检测到，所以可能会出现非预期的情况

**Comment by hzinchengdu** [comment]
怎么取消英文词上屏时前面自动加空格的这个功能。

**Comment by boomker** [comment]
> 怎么取消英文词上屏时前面自动加空格的这个功能

将[这行](https://github.com/boomker/rime-fast-xhup/blob/a877ed5632de7edf133fe116de05eb601f7e838f/flypy_xhfast.yaml#L50) 注释掉。

取消中英混合候选词条的中的空格，将[这行](https://github.com/boomker/rime-fast-xhup/blob/a877ed5632de7edf133fe116de05eb601f7e838f/flypy_xhfast.custom.yaml#L102)注释掉

**Comment by hzinchengdu** [comment]
第一个链接404了，第二个链接的代码变更了。

**Comment by boomker** [comment]
> 第一个链接404了，第二个链接的代码变更了。

 更新了

**Comment by boomker** [comment]
现在可以临时关闭这个功能了
<img width="223" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/575f82de-3162-45c6-8b2d-4131fa7d0a60">
