### ISSUE TITLE
更新当前最新版本方案后，小狼毫部署后无法输入汉字

### ISSUE THREAD

**Issue by Z-Vaj** [boomker/rime-fast-xhup#35]
![image](https://github.com/boomker/rime-fast-xhup/assets/32755771/f8fd9aba-8448-42d9-98ea-7df9af2d16c5)
![image](https://github.com/boomker/rime-fast-xhup/assets/32755771/60d7ae81-7d47-48e6-8649-aed386f1afdd)
如题：直接把您的最新方案downing下来部署后，无法输入汉字，以上是我小狼毫的版本和输入时的显示，电脑是系统Windows11

**Comment by boomker** [comment]
建议升级 Librime 版本，有报错日志吗
你先把这个[文件](https://github.com/boomker/rime-fast-xhup/blob/7d584a388ab3e06973b44c5340eec61d8045a86e/flypy_xhfast.dict.yaml)里的大词库注释了，再部署

**Comment by Z-Vaj** [comment]
谢谢可以了
