### ISSUE TITLE
置顶词功能否升级成固定词

### ISSUE THREAD

**Issue by hzinchengdu** [boomker/rime-fast-xhup#36]
`pin_word_record.lua`的
置顶词能否像搜狗输入法那样固定位置，目前加词的话只能像数组一样从第一位开始配置，能否实现从1到10固定位置的效果。

理想的样子是custom_phrase.txt中的权重完全变成固定位置的功能。

**Comment by hzinchengdu** [comment]
另外置顶词中中西文夹杂时，如何取消中间自动加空格。
比如
`["iosb"] = { "iOS版", "iOS版本", },`
输出的是
`iOS 版`

**Comment by hzinchengdu** [comment]
还是不太会用，
比如我填入了
`["a"] = { "啊", "按", "、"},`，
希望输入a编码时的前3位固定是这3个，但是在下面两个文件的位置填上后都没有达到理想状态。

我分不清`pin_word_record.lua`和`custom_phrase.txt`之间的区别。

![image](https://github.com/boomker/rime-fast-xhup/assets/126546789/58bca595-b4ef-4e1f-ac3a-b7a7b6f2194c)
![image](https://github.com/boomker/rime-fast-xhup/assets/126546789/42367a23-9321-49f8-9221-d41303d3f17a)

**Comment by boomker** [comment]
> 固定位置，目前加词的话只能像数组一样从第一位开始配置，能否实现从1到10固定位置的效果

在`lua/pin_word_record.lua` 里，在花括号`{按从左到右的顺序}` 就是从1 到  N 的固定位置


> 如何取消中间自动加空格

这个是一个 Lua 的功能， 可以取消，注释或删除[这行](https://github.com/boomker/rime-fast-xhup/blob/e5eee4b862c275d288e507c9f29d9928a79abda0/flypy_xhfast.schema.yaml#L101)

> 我分不清pin_word_record.lua和custom_phrase.txt之间的区别

我的建议是，单字母编码，如 "a 啊 按 " 放到 `custom_phrase.txt` 里， 多字母的放到`pin_word_record.lua` 里

**Comment by hzinchengdu** [comment]
好的，但是测试发现标点符号并不会出现在面板上，在lua中设置后也不会出现。
```
按	a	9998
je suis	a	9997
后	a	9996
、	a	9995
!	a	9994
```
![image](https://github.com/boomker/rime-fast-xhup/assets/126546789/51966e44-9f91-4c66-b8d7-ed3127752d48)

**Comment by hzinchengdu** [comment]
测试只在`pin_word_record.lua`中配置，发现并不能正常识别。
```
local pin_word_records =
{
	["a"] = { "我", "!", "@", "逗号", },
}
return pin_word_records
```

![image](https://github.com/boomker/rime-fast-xhup/assets/126546789/1cbec8cc-96f5-44db-8127-357e270fc6cd)

**Comment by boomker** [comment]
<img width="202" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/584e72e9-f1aa-4d33-aae5-eaf0f3323071">


<img width="111" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/3e1a5414-9008-4e18-8452-ff0aa00fee9b">


你这种属于自定义编码， 放到`custom_phrase.txt`  里， 需要注意的是要以`Tab` 符号隔开

**Comment by hzinchengdu** [comment]
测试aw可以，但是单个编码a就不生效了。

**Comment by boomker** [comment]
单个编码用来自定义编码，会让 Rime 输入法程序困惑的，因为这和已有的字表或内置码表相冲突的。

**Comment by hzinchengdu** [comment]
能实现单个编码用来自定义短语吗，或者自己改词库的话该怎么操作。
因为我需要高频用到单个编码用来打标点之类的符号，其他平台的各种输入法都这样用。
这些编码也不需要参与造词。

**Comment by boomker** [comment]
单个字母来编码标点符号，这个不推荐，也似乎没法实现。 其他平台有这样的吗， 截图看下

你可以这样敲 `/bd`, 效果是这样的：
<img width="151" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/e1497566-3dcc-4384-8b51-51add4d12597">

你可以自定义， 比如： `/ab`

**Comment by hzinchengdu** [comment]
其他平台有的。图中的用法我知道，但是直接用单个字母编码在各种设备上基本都适用，也比较有一致性（比如手机上就没办法用`/`引导）。这种用法在有些五笔方案上有，我是借鉴到了拼音上。

单个字母还可以用来输入标点以外的字符，比如日语、拼音……

看了[雾凇拼音的文档](https://dvel.me/posts/rime-ice/#%e8%87%aa%e5%ae%9a%e4%b9%89%e6%96%87%e6%9c%ac)，它能够单个字母编码，因此应该可以实现。

**Comment by boomker** [comment]
还有一种方法，就是用其他的引导符来实现， 比如这样：
<img width="159" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/5d2ae5cc-b6fe-4518-9aea-2e4b80e4bae4">

<img width="80" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/e1c490b9-c776-4d8c-9623-c59d000a5a31">

**Comment by hzinchengdu** [comment]
这些我全部知道，我都使用过，最后选择了使用编码方式来输入标点。
而且我已经使用这种方式输入标点多年了，也参考了国家标准整出了一套很完备的标点输入方案，不再愿意改变习惯。

我是今年开始尝试使用小狼毫，但因为一些功能的缺失，一直很难作为主要的输入工具。

问题不是“单个字母来编码标点”，而是实现一个和其他输入法一样的完整的自定义短语功能，这个应该和其他输入法一样拥有最高的优先级，这当然也包括“单个字母编码可以自定义任何字符”，默认不参与造词，有些字符可选参与造词。

Rime远比普通输入法强大，其他输入法有的功能，一定有一种方法也可以实现，解决这样的冲突问题。

**Comment by boomker** [comment]
经过尝试， 只能实现这种：
<img width="148" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/fa0e2992-a783-4a61-b476-a43595e16da7">

**Comment by hzinchengdu** [comment]
太好了，刚刚看到雾凇拼音的[自定义短语](https://github.com/iDvel/rime-ice/blob/main/custom_phrase.txt)默认支持。

另外`flypy_xhfast.schema.yaml`[半角符号](https://github.com/boomker/rime-fast-xhup/blob/master/flypy_xhfast.schema.yaml#L262)设置没有`default.yaml`的[半角符号](https://github.com/boomker/rime-fast-xhup/blob/master/default.yaml#L102C1-L102C14)多，我第一次上手操作时花了很久才理清哪些选项会真正生效，因为一些配置与`default.yaml`重合。当时我就有“为什么不把这个选项也像[全角符号一样引用起来](https://github.com/boomker/rime-fast-xhup/blob/master/flypy_xhfast.schema.yaml#L261C4-L261C5)的想法。

建议把下面的问题写入到readme中，以下问题是我在配置过程中遇到的，并花了一些时间才解决的，省事的办法是以“网友遇到的一些问题”的形式贴出来。
- 解决[无法恢复默认的引号输入方式](https://github.com/boomker/rime-fast-xhup/issues/22)
- [Windows部署的前提](https://github.com/boomker/rime-fast-xhup/issues/23#issuecomment-1999813101)，否则无法部署成功
- [词库切换成直接引导](https://github.com/boomker/rime-fast-xhup/issues/30)的方法
- 取消[中英文混合词的中间会自动加空格](https://github.com/boomker/rime-fast-xhup/issues/36#issuecomment-2067600617)的方法

**Comment by hzinchengdu** [comment]
有没有办法或者借助一些工具实现`custom_phrase.txt`里的权重数值越小，候选项越靠前，或者把权重完全变成固定位置，但不是`pin_word_record.lua`中的对象形式。
因为这样更简单理解，也与其他输入法的形式一致，如果在别的输入法平台有一堆自定义短语，在rime中不好处理。

**Comment by boomker** [comment]
> 建议把下面的问题写入到readme中

已更新到 Readme 中，请查看 FAQ

> 有没有办法或者借助一些工具实现custom_phrase.txt里的权重数值越小，候选项越靠前，或者把权重完全变成固定位置，但不是pin_word_record.lua中的对象形式。
因为这样更简单理解，也与其他输入法的形式一致，如果在别的输入法平台有一堆自定义短语，在rime中不好处理。


权重越小， 候选项位置越靠前，这个目前没有想到好的实现方式
自定义短语按固定顺序位置来排列， 可以用 `YAML`  配置文件以列表的形式来实现， 但是得代码里做解析，空了我试着实现

**Comment by hzinchengdu** [comment]
好的，那目前怎么让单字母编码定义的任意字符生效，哪个Lua引起的冲突。

**Comment by boomker** [comment]
> 好的，那目前怎么让单字母编码定义的任意字符生效，哪个Lua引起的冲突。

 开启[这行](https://github.com/boomker/rime-fast-xhup/blob/fbd9ee18731d5bd269485d83e5d6d8bb1e6a1934/flypy_xhfast.schema.yaml#L82)

注释掉[这行](https://github.com/boomker/rime-fast-xhup/blob/fbd9ee18731d5bd269485d83e5d6d8bb1e6a1934/flypy_xhfast.schema.yaml#L98)

另外，  readme 中有写分号 `;` 前缀快捷输入符号的功能， 你试试看体验如何

**Comment by hzinchengdu** [comment]
明白了。
分号引导方式输入我以前也用过，后来放弃了。现在更习惯中文输入法默认全部标点是英文，中文标点只用26个英文字母打。虽然我不是程序员，但我觉得这种方式应该对程序员比较友好。

我注意到有些字显示的并不全，比如我想打`cc`上屏`艹`，但翻了两页就没有词了，怎么显示的更全一些。

**Comment by boomker** [comment]
了解，每个人输入习惯不同。我是一般进入到 IDE  环境会默认标点使用英文的，离开这个环境就是用输入的设定。

> 我注意到有些字显示的并不全

这个在 Readme 有写，默认我的方案里不启用生僻字， 要输入生僻字， 可以通过 ` ~`  偏傍部首反查方式来输入，比如：
<img width="118" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/70fdf8f2-a6dc-4870-ac6d-bb5f1c86052e">

**Comment by hzinchengdu** [comment]
这样输入有点复杂……怎么启用生僻字，能否提供选项。
微软拼音和搜狗拼音是默认启用生僻字，手机上应该也是。
我是想尽量贴近这些大众输入法的使用习惯。

**Comment by boomker** [comment]
这个问题之前也纠结过， 启用生僻字的话， 会有这样几个问题：
1. 启用哪些生僻字， 这些生僻字读音如何标注正确，形码也要编码正常， 得有一个批量方式
2. 使用者使用的字体不支持生僻字， 会在候选菜单列表有显示不出来的情况。

**Comment by hzinchengdu** [comment]
这确实是个问题。
可以参考国标，比如GB18030—2005甚至GB18030-2022，但怎么搜集这些字我还不知道。或者只处理现有的只能反查的生僻字；
读音的话我记得python的pypinyin库能处理，这些字的读音一定有一些只有古代才用；不清楚雾凇拼音里的生僻字有多少，它那里面有的就足够了。
生僻字的形码可以不进行编码。

使用者的字体不支持生僻字，这个可以在文档中进行说明，建议使用者安装下面这些字体多的字库，最新版小狼毫已经支持选择多种字库了。基本上第一个思源黑体已经够用了，只要不是特别生僻的的字现在都会显示。

- [思源黑体](https://github.com/adobe-fonts/source-han-sans/releases)的区域大字库`Language Specific OTFs Simplified Chinese (简体中文)`
- [MiSans L3](https://hyperos.mi.com/font/download)
- [阿里巴巴普惠体 L3](https://www.alibabafonts.com/#/font)

比如“𰻝”（biáng）字思源黑体就支持，像影视剧或出版书籍中的“认𪨊（rèn sóng）”的“𪨊”（sóng）只有L3级别的字库才支持，手机上支持也是最近的事情。

L3级别的字体我想到的是在[MiSans](https://hyperos.mi.com/font/rare-word)官网抓取，但这是个大工程，我的建议是放弃。

**Comment by boomker** [comment]
> 可以参考国标，比如GB18030—2005甚至GB18030-2022

新增了扩展字表，可以输入 L1 和 L2 级别的大多数字了。

**Comment by boomker** [comment]
> 好的，那目前怎么让单字母编码定义的任意字符生效，哪个Lua引起的冲突。

最新项目配置可以不用考虑冲突了，可以开启所有`Lua` 功能
