### ISSUE TITLE
快捷指令相关问题

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#37]
猜测是不是和快捷指令有关系
<img width="84" alt="截屏2024-04-22 17 13 11" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/4f129a58-6702-4c15-8025-d872f7f61e7d">
<img width="94" alt="截屏2024-04-22 17 12 39" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/0589482a-e77a-4dc5-9477-7e1329061625">

**Comment by boomker** [comment]
我这边没有这种情况， 可以把你的 `lua/launcher_config.lua` 配置发我看看吗

**Comment by boomker** [comment]
我的建议还是， 将触发前缀改成比较特殊的， 用 `/` 开头， 我这边是没出现问题的。

**Comment by Hodwe** [comment]
之前说的那个问题部署之后就好了，有2个新的问题
1、快捷指令的触发词无法删除，例如我的触发词是u，输入之后通过backspace无法删除
2、我也希望通过符号作为触发词，但是有一点一直没弄明白，我想用;作为触发词，在
speller:
  alphabet:
下面已经将;添加进去了，但是仍然会直接输出;，导致不能将;作为触发词

**Comment by boomker** [comment]
1. `Backspace`  键是用来回到上一级菜单的，`Enter` 键用来进到下一级菜单，` Esc` 键用来取消操作
2. `;`可以作为触发键， 你可能需要改成 [这行](https://github.com/boomker/rime-fast-xhup/blob/57bb5b093ae164f46ffac52df47b18addf89c2b1/flypy_xhfast.schema.yaml#L265) 的样子

**Comment by Hodwe** [comment]
好的，谢谢，明白了，我试试

**Comment by Hodwe** [comment]
有一点可能理解不是很对，backspace作用是回到上一页，但是一旦回到头了，也就是回到了触发词这里，backspace这时的回到上一页的功能就没用了，这时能否恢复backspace的删除功能，ios上不太方便

**Comment by boomker** [comment]
> 能否恢复backspace的删除功能，ios上不太方便

可以的， 已经恢复了， 之前没考虑手机端。。。

**Comment by Hodwe** [comment]
已经更新了，现在能删除了，新的问题：
1、快捷指令会进行记忆，但是根据记忆的二级菜单不能直接输入，反而觉得不需要记忆，直接进入主菜单，也就是根据记忆直接进入上一次残留的二级菜单后，可以直接输入，但是不能通过首字母输入（说的有点燃，看视频）
2、二级菜单的首字母输入，无法直接上屏内容，希望输入首字母后，不要再显示一次菜单，直接输出即可，也就是视频内的，输入vv后，再输入c进入卡号，接下来再输入a时，直接输出身份证1就行，不用再弹出一个菜单


https://github.com/boomker/rime-fast-xhup/assets/158744320/3674b3d6-6c04-401a-9dff-39761db63688

**Comment by boomker** [comment]
1. 看了几遍视频， 没看懂二级菜单被「记忆」的问题。每次不都从主菜单进入的嘛，我这边没有复现出来这个问题
2. 二级菜单直接上屏这个想法挺好， 但是我还没想到如何实现。目前暂时只能先弹出一个菜单，然后空格键上屏。

**Comment by Hodwe** [comment]
https://github.com/boomker/rime-fast-xhup/assets/158744320/fb4a1635-5735-4fba-8fb4-612079a3ae56

**Comment by Hodwe** [comment]
还有一个问题就是，如果我的标题前面本身就是英文，似乎无法在前面添加字母，然后借助输入字母进行输出
<img width="137" alt="截屏2024-04-26 13 57 12" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/0403c06a-655b-4def-adaf-63104b58d61b">

**Comment by boomker** [comment]
> 还有一个问题就是，如果我的标题前面本身就是英文，似乎无法在前面添加字母，然后借助输入字母进行输出 

不用添加字母了， 你按一个小写的字母就可以触发大写开头的菜单名


你等会儿拉一下更新， 感觉你还是在用老的代码，最新的代码没有二级菜单会被记忆的情况

**Comment by Hodwe** [comment]
我之前的就是最新的，用脚本关注着你的更新😂刚又拉了最新，现在好了，感谢

**Comment by Hodwe** [comment]
> 我之前的就是最新的，用脚本关注着你的更新😂刚又拉了最新，现在好了，感谢

这一步的时候已经好了，后面又拉了一版，问题出现在：
触发词vv-c卡号-再输入a的即将弹出对应的那一个选项的时候，失败了

**Comment by boomker** [comment]
>  再输入a的即将弹出对应的那一个选项的时候，失败了

有录屏吗， a 开头的那个菜单名称是什么， 
现在二级被选中候选项不会弹出来了， 会直接上屏的

**Comment by Hodwe** [comment]
https://github.com/boomker/rime-fast-xhup/assets/158744320/a7f0d7aa-350d-40b8-be23-d1493049ffeb

**Comment by Hodwe** [comment]
我回去测试一下Mac

**Comment by Hodwe** [comment]
https://github.com/boomker/rime-fast-xhup/assets/158744320/f14e5893-d96f-407f-8d6c-c9d7669ecc97

**Comment by boomker** [comment]
我这边没有这样的问题，你那边可能是和其他 filter 相冲突了 ，你尝试一下把其他带有 ` lua_filter` 的行注释掉
<img width="502" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/ba3b6048-e1dc-4705-b80d-3a513401e89c">

**Comment by Hodwe** [comment]
mac还没试，ios不行

**Comment by Hodwe** [comment]
mac删了正常，是不是得把launch放在lua的最下面，我放最下面就好了，不知道是什么原理，ios放在最下面也可以

**Comment by boomker** [comment]
> 我放最下面就好了，不知道是什么原理

放最下面防止其他的` filter ` 处理快捷指令的候选项
