### ISSUE TITLE
custom_phrase.txt自定义，有些生效有些不生效

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#38]
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/1dcc8a4d-4957-428a-bc88-95a450706f8f)

图中列出的6个不能用，但是其余四个是正常的

```txt
calmwaves	cw	10000
🐞	bug	10000
📤	fab	10000
💬	hvf	10000
✍🏻️	vrx	10000
🍉	iig	10000
🎛	zuj	10000
🙋	by	10000
➖️➖️➖️	ffg	10000
🚢	ird	10000
151xxxxxxxx	sjh	10000
```
感觉像是这6个码没有对应单字，比如bug就不行
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/fa1d0293-5081-4ed8-b641-5757c06afa6a)

但是hvf就可以
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/ff6edee6-f5b7-49a0-abb9-186958a1b311)

**Comment by boomker** [comment]
已经修复了，重新拉下项目配置试试看

**Comment by calmwaves111** [comment]
好啦修好啦(大佬也修太快了

**Comment by trevim99** [comment]
🙋‍♂️

boomker 大佬

請問 custom_phase.txt 里的  <br>是
换行符号，我如果想 
設定自定義短語 原样输出 <br> 
請問在  custom_phase.txt  要怎麼設置？

(請問   custom_phase.txt  可使用的轉義符是什麼？)

謝謝🙏




![image](https://github.com/user-attachments/assets/9853cbee-6ccd-4c6f-b6f9-7733cb6454a6)

**Comment by trevim99** [comment]
另外请问 打  tab  时
候選框 编号7 的  tab 符(原义 )
是怎么做出来的？ 谢谢
🙏 

![image](https://github.com/user-attachments/assets/4df67fef-a2f5-4739-abf9-f40b26ff704f)

**Comment by boomker** [comment]
1. 原样输出`<br>`， 这个需求比较小众，没考虑过
2. 目前支持的特殊符号就只有`<br>`， 没有其他了
3. `Tab`符号是通过`OpenCC`实现转换的，这个符号可以被复制的，也能在`Nvim`中，通过按下`Ctrl-v`+`Tab` 输入

**Comment by trevim99** [comment]
多謝回復

我都問些怪怪的問題 😓
