### ISSUE TITLE
左右圆括号是有其他用处吗，我现在不能直接上屏了

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#39]
我的配置是这样的 
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/5eef6fa2-da24-468b-8113-653e7d29a247)
 
但是现在打出来是这样

![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/a418d2b4-a771-4c82-a93f-da6ef6ea1b43)

**Comment by boomker** [comment]
修复了， 很奇怪， 之前没发现，没遇到

**Comment by calmwaves111** [comment]
okk，修好啦
