### ISSUE TITLE
辅码造词功能不能进入用户词库

### ISSUE THREAD

**Issue by zigeweiwu** [boomker/rime-fast-xhup#4]
![动画](https://github.com/boomker/rime-fast-xhup/assets/95293685/ffb9b363-bfbd-4c69-8939-78edf7e6dadb)
辅码没有自动造词

**Comment by BigOldTree** [comment]
用户词库中的“关见”是带“[”符号的

![关键](https://github.com/boomker/rime-fast-xhup/assets/95293685/c4ecfbe4-70c9-40f0-8a04-327c3f3f4f7c)

**Comment by boomker** [comment]
这个问题我可能没法完美解决, 之前反复调整配置测试, 还是没法达到想象中那种效果
目前能支持的造词模式只有:
![iShot_2023-05-30_22 11 54](https://github.com/boomker/rime-fast-xhup/assets/19751472/ce8f3941-fea1-4522-bc19-3e2cdd82dbc7)

**Comment by BigOldTree** [comment]
> 这个问题我可能没法完美解决, 之前反复调整配置测试, 还是没法达到想象中那种效果 目前能支持的造词模式只有: ![iShot_2023-05-30_22 11 54](https://user-images.githubusercontent.com/19751472/241995054-ce8f3941-fea1-4522-bc19-3e2cdd82dbc7.gif)

我现在自用的方案是可以的，使用的是小鹤形码作为基础码表。
![动画](https://github.com/boomker/rime-fast-xhup/assets/95293685/e30e031a-c5fc-4f0e-acdb-441f9bf77683)

**Comment by BigOldTree** [comment]
> 我发现这样使用造句会比较符合期望 
是的，如果这样造词的词组可以进入用户词库就可以了

**Comment by BigOldTree** [comment]
l下面是ibrime-lua 项目的wiki ，感觉可以使用lua 脚本转化一下上屏的编码。截取掉“[” 实现自动造词

https://github.com/hchunhui/librime-lua/wiki/Scripting

**Comment by boomker** [comment]
> l下面是ibrime-lua 项目的wiki ，感觉可以使用lua 脚本转化一下上屏的编码。截取掉“[” 实现自动造词
> 
> https://github.com/hchunhui/librime-lua/wiki/Scripting

---------
空了我研究一下, 最近刚入职新公司有些忙
自动造词, 我的理解是:  通过非辅助码, 输入法根据用户的输入码和上屏的的字词来自动进入到用户字典里是吧
之前看过一个 电脑极光的 Rime 方案, 里面有类似的 lua 脚本实现用户最近输入字词再次输入时会置顶,  不过写得太复杂了, 能力有限, 还没研究透

**Comment by boomker** [comment]
辅码造词换成了 ` 符号来引导精准造词，最新配置实现了一次造词上屏后即可进入用户词库且再次输入置顶。最新的`librime` 库在自动造词的体验上有了优化， 逐字选词上屏后，下次输入同样也会置顶了。
