### ISSUE TITLE
我想把rq->日期放到首位

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#40]
我把date_time.lua稍微改了下，输入码改成了rq
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/0487e348-452f-45f1-9872-07dfe98691ce)
但是原先我打rq这些日期 都是在最开头的，现在突然从第三位开始了

![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/72cb5250-df92-4a1b-bedb-870933e88412)

我刚开始以为是权重的问题，但是我改成了999999，还是不行，不知道是哪里出了问题

**Comment by boomker** [comment]
新配置支持了`rq`了， 
这个被放到第三位，是被长词优选功能给影响了。
在[这行](https://github.com/boomker/rime-fast-xhup/blob/7faa840eddf26d062ef7a5950a93fe2a40aadcde/flypy_xhfast.custom.yaml#L63)添加需要忽略的输入编码
