### ISSUE TITLE
不小心将某个字删除如何恢复

### ISSUE THREAD

**Issue by Admaks** [boomker/rime-fast-xhup#41]
不小心将字删除如何恢复

使用 Ctrl+D 不小心将某个字删除，现在打不出这个字了，如何恢复

**Comment by boomker** [comment]
在这个文件 [`lua/cold_word_record/drop_words.lua`](https://github.com/boomker/rime-fast-xhup/blob/7faa840eddf26d062ef7a5950a93fe2a40aadcde/lua/cold_word_record/drop_words.lua), 找到对应的字， 删除即可恢复
