### ISSUE TITLE
引用tools疑问

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#42]
现在很多lua都引用了tools内的变量代码，例如commit_history.lua，如果我并不想进行引用，应该怎么处理，有一个思路吗？我后面可以自己改一改，谢谢

**Comment by boomker** [comment]
引用的` tools` 内的 Lua， 主要是为了方便解析配置数据， 不想引用这些，可以自己用原始的`librime-lua`提供的 API 来写。

比如[这行](https://github.com/boomker/rime-fast-xhup/blob/b3960f59433a81a56f1673c2c7095555da37cacf/lua/commit_history.lua#L20)

可以写成：
```lua
local excluded_types = config:get_list("history" .. "/excluded_types") or {}
local set = {}
for i = 0, list.size - 1 do
    local v, _ = list:get_value_at(i).value
   table.insert(set, v:gsub(" ", ""))
end
```

**Comment by Hodwe** [comment]
还是不太会写，我用旧版吧
大佬能不能在.gitignore文件内添加一个.DS_Store，mac总是提示在你的git文件中添加了这个文件，可以排除一下，谢谢

**Comment by boomker** [comment]
`.DS_Store` 添加了， 这个文件没在我的仓库里，你那边的提示，方便的话， 可以截图看看吗

**Comment by Hodwe** [comment]
就是在vscode里面会提示git里面新增了.DS_Store文件，每次我只能删除，.gitignore文件是git的屏蔽文件，我克隆你的git仓库时，里面是有的，是一个隐藏文件夹，可以编辑需要屏蔽的文件或文件夹

**Comment by boomker** [comment]
好吧，之前确实我这边没遇到这个情况，感谢反馈， 已添加到`.gitignore`, 以后应该不会了。

**Comment by Hodwe** [comment]
已经好了
大佬看看这个lua，功能好像比较多，觉得英文模糊输入挺好用，有空看能否制作一个lua
https://github.com/zhuangzhemin/Rime/tree/master/lua/english

**Comment by boomker** [comment]
> 已经好了 大佬看看这个lua，功能好像比较多，觉得英文模糊输入挺好用，有空看能否制作一个lua https://github.com/zhuangzhemin/Rime/tree/master/lua/english

可以考虑弄，暂时可以实现一键切到英文输入模式(`Ctrl+g`)

**Comment by Hodwe** [comment]
谢谢，等大佬的更新
