### ISSUE TITLE
有关中文释义

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#43]
如果想用中文释义的功能，必须得另外弄一个英文方案和码表是吗？

**Comment by boomker** [comment]
目前来说，只能这样实现。英文词典和反查词典还不能合二为一
之前看到未来` Squirrel` 版本会支持合二为一的这种词典格式。

**Comment by Hodwe** [comment]
好的，谢谢

**Comment by Hodwe** [comment]
在这问一个其他的问题：
我看lua新增了最近时间的输入
    ["/wqt"] = { -2, "前天" },
    ["/wzt"] = { -1, "昨天" },
    ["/now"] = { 0, "此刻" },
    ["/wjt"] = { 0, "今天" },
    ["/wmt"] = { 1, "明天" },
    ["/wht"] = { 2, "后天" },
    ["/wuz"] = { -7, "上周" },
    ["/wxz"] = { 7, "下周" },
    ["/wlk"] = { -7, "上周" },
    ["/wnk"] = { 7, "下周" },
    ["/wuy"] = { get_month_sameday("before"), "上个月今天" },
    ["/wxy"] = { get_month_sameday("after"), "下个月今天" },
    ["/wlm"] = { get_month_sameday("before"), "上个月今天" },
    ["/wnm"] = { get_month_sameday("after"), "下个月今天" },

我之前有个旧的时间lua，尝试借助ChatGPT融合没有成功，大佬能给一些思路或者帮我融合一下吗？感谢😂
[time_translator.txt](https://github.com/boomker/rime-fast-xhup/files/15314566/time_translator.txt)

**Comment by boomker** [comment]
融合什么功能，我看这个文件包含了很多功能， 我的建议是拆出一部分功能到单独文件里比较好，维护起来比较容易。
看到几千行的代码，有种如临大敌的感觉。比如可以拆成这几块：时间日期; 农历; 节气。

**Comment by Hodwe** [comment]
我需要的是：
你的关于时间的lua中的最近时间的相关功能，例如今天、昨天的日期等等，想加进我自己的时间lua中，不行的话我就再弄一个新lua吧

**Comment by boomker** [comment]
你还是弄一个新的吧，或者直接用我的呗，也不用折腾了。
