### ISSUE TITLE
`pin_word_record.lua`能否实现自动修剪重复的词

### ISSUE THREAD

**Issue by hzinchengdu** [boomker/rime-fast-xhup#44]
如果反复按`Ctrl+T`，会重复添加，能否实现自动修剪重复项。
```
["d"] = { 	"的",
"的",
"的",
"的",
```

还有一些使用时遇到的问题
1. 新版本中一些短语添加后不会显示，不管是在`pin_word_record.lua`中还是在`custom_phrase.txt`中。
比如
```
["ap"] = { "安排", "Affinity Photo", "Affinity Publisher", },
["ai"] = { "爱", "Illustrator", "Adobe Illustrator", },
```
或
```
ai	爱	3
ai	Illustrator	2
ai	Adobe Illustrator	1
```
2. 在“候选词个数”为`10`的情况下，非按0没有达到预期的效果（词组，单字不影响）。
![2  非单字时上屏异常](https://github.com/boomker/rime-fast-xhup/assets/126546789/ad60ed0a-d929-4571-b757-daf81468acac)

3. 如何取消“词组唯一时自动上屏”的功能。
![3  唯一时自动上屏](https://github.com/boomker/rime-fast-xhup/assets/126546789/41844a63-07dc-41fe-86eb-b2129228bf7f)

4. 新版本的置顶词图标有的显示，有的就不显示。
```
pin_word:                     # 词条置顶配置
  pin_word_key: "Control+t"   # 词条置顶快捷键, 优先级高于`key_binder`全局配置
  word_quality: 1000
  comment_mark: "🔝"          # 不能留空
  excluded_types: ["flypy_key_help", "easy_en", "radical_lookup"]
```

5. `custom_phrase.txt`能否也实现图标或字体颜色相关的提示。
6. 新版本删除了`flypy_xhfast.custom.yaml`后，怎么实现“直接辅码引导”。

**Comment by boomker** [comment]
> 1. 如果反复按Ctrl+T，会重复添加，能否实现自动修剪重复项

已实现，重复按`Ctrl+T`会在添加和取消两个动作之间切换

> 2. 新版本中一些短语添加后不会显示

这个已经修复了。需要注意的是在` custom_phrase` 里添加，要用`tab`(⇥)符号隔开

> 3. 在“候选词个数”为10的情况下，按0没有达到预期的效果

这个还没找到解决办法，我问问社区大佬

> 4. 如何取消“词组唯一时自动上屏”的功能

现在默认是关闭的，增加了一个开关

> 5. 新版本的置顶词图标有的显示，有的就不显示

现在都默认显示了

> 6. custom_phrase.txt能否也实现图标或字体颜色相关的提示

添加了一个图标(📌)来提示

> 7. 新版本删除了flypy_xhfast.custom.yaml后，怎么实现“直接辅码引导”

在配置文件里有写的。
    # 如果希望无论有无 [ 均可引导, 取消下行注释, 放到当前文件`algebra`节点下
    # speller/algebra/@next: derive/[[]//

**Comment by hzinchengdu** [comment]
> 已实现，重复按Ctrl+T会在添加和取消两个动作之间切换

试了一下，如果一个词很陌生或完全是自定义的，误触后就消失了，这个快捷键只是单纯的添加功能体验会更良好一些。
能否实现像数组一样去重，这个行为在后台自动完成。
