### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by MO-0518** [boomker/rime-fast-xhup#46]
作者大大 好像少了一个custom文件

**Comment by boomker** [comment]
是少了`custom_phrase.txt` 吗？ 
我看项目里是存在的啊，你重新拉一下项目再试试

**Comment by MO-0518** [comment]
> 是少了`custom_phrase.txt` 吗？ 
> 
> 我看项目里是存在的啊，你重新拉一下项目再试试

少了一个flypy_xhfast.custom.yaml

**Comment by boomker** [comment]
这个文件我移出了， 不再使用 custom 配置文件了。

**Comment by boomker** [comment]
恢复了，上传了一份

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
