### ISSUE TITLE
部分词语多次上屏后，无法固定词频

### ISSUE THREAD

**Issue by haosemusi** [boomker/rime-fast-xhup#47]
比如：输入“杜希夷”，反复选择上屏多次后，该词条还是没有固定在最前面

![WechatIMG3](https://github.com/boomker/rime-fast-xhup/assets/22735955/6157c5a6-aaa1-4280-8314-ef00dac3d35e)

**Comment by boomker** [comment]
你用的是默认配置吗， 我这边一次上屏，下次就置顶了
<img width="110" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/5a4588e4-3787-4287-9cdc-6d4afe19d2d8">

**Comment by haosemusi** [comment]
就是用的默认配置。
您可以再试试“王红莉”，输入‘whhsli‘后，通过 Tab 键一个字一个字的筛选出来(先通过 tab键 定位到第一个字的读音，选出 王，再通过 Tab 键筛选出 红，最后选出莉)，好像就没有记住词频了。

**Comment by boomker** [comment]
我知道问题了， 应该是你的输入法程序版本或者是你的` librime` 不是新的。 在 `Readme`里能找到`librime`更新地址的
<img width="106" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/e7f1c714-dedc-43a8-a23e-fd752359098a">

**Comment by haosemusi** [comment]
尝试更新了最新的鼠须管客户端，就正常了，应该就是你说的这个原因了。
感谢！！
