### ISSUE TITLE
按照教程，修改为默认引号输入方式不生效

### ISSUE THREAD

**Issue by rwerplus** [boomker/rime-fast-xhup#48]
Q: 恢复默认单双引号 ' " 输出方式
A: 在[主配置文件](https://github.com/boomker/rime-fast-xhup/blob/a877ed5632de7edf133fe116de05eb601f7e838f/flypy_xhfast.schema.yaml)里注释这[两行](https://github.com/boomker/rime-fast-xhup/blob/a877ed5632de7edf133fe116de05eb601f7e838f/flypy_xhfast.schema.yaml#L266-L267)

按照这个方法注释掉后重新部署输出的引号依然是“”     ""    ''''

**Comment by boomker** [comment]
这会儿更新了一版，恢复了单双引号

**Comment by rwerplus** [comment]
刚刚更新了，但是/so我没有找到这个命令，我自己本地改了很久，改不好了😢

**Comment by boomker** [comment]
`/so` 是新加上的，重新拉取项目文件后得部署了才会有，确保是完整的拉取项目文件，我这边是正常可用的，也不需要改什么。

单双引号还是没恢复吗， 这个默认已经恢复了， 也不用改了。
