### ISSUE TITLE
flypy_xhfast.custom.yaml 此文件是不是忘记上传了？

### ISSUE THREAD

**Issue by a444739916** [boomker/rime-fast-xhup#49]
flypy_xhfast.custom.yaml 此文件是不是忘记上传了？

**Comment by boomker** [comment]
我是把这个文件给移出了，不再使用` custom` 了。

**Comment by a444739916** [comment]
> 我是把这个文件给移出了，不再使用` custom` 了。

留着多好，自定义的东西写schema中的话，有新版本的时候，schema文件都不敢覆盖了

**Comment by boomker** [comment]
好吧，还是加上一个`custom` 文件，上传一份，然后加到`.gitignore` 里，不再更新覆盖用户自定义的配置

**Comment by a444739916** [comment]
> 好吧，还是加上一个`custom` 文件，上传一份，然后加到`.gitignore` 里，不再更新覆盖用户自定义的配置

另外还有一个问题，在输入的时候，能关闭中英混合输入吗？开启直接辅码以后，在输入辅码的时候老是跳出英文单词

**Comment by boomker** [comment]
> 开启直接辅码以后，在输入辅码的时候老是跳出英文单词

关闭英文输入方案就没有英文了。


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
