### ISSUE TITLE
word_append_space.lua

### ISSUE THREAD

**Issue by ufo169** [boomker/rime-fast-xhup#5]
如果方便添加一个功能，符号顶屏候选时，同样实现候选左边添加空格，想用在英文方案。

**Comment by boomker** [comment]
如果用在纯英文方案里, 我感觉应该是给符号右边添加空格.  一般来说英文符号后跟英文单词要有空格
这个我有空了尝试写下 lua 来实现

**Comment by ufo169** [comment]
> 如果用在纯英文方案里, 我感觉应该是给符号右边添加空格. 一般来说英文符号后跟英文单词要有空格 这个我有空了尝试写下 lua 来实现

多谢！使用过[BlindingDark/rime-easy-en](https://github.com/BlindingDark/rime-easy-en)方案，可以分词，比较遗憾的是因为经过lua处理，无法记忆用户词典。我也尝试，在单词前面添加了空格，可以简单实现自动分词，效果差些，但是可以恢复用户词典的作用，主要问题是，第一个单词带有空格，其它格式挺好的。另外一种尝试，使用你的自动空格lua打单词和easy-en方案自动分词打句子，效果不错，用户词典可以记忆单词，连续输入增强的效果不错，虽然无法记忆句子，不过影响不大。主要就是，符号顶屏时还无法符合英文空格格式

**Comment by boomker** [comment]
@ufo169 ，适用于英文输入方案的自动空格来了，参考: https://github.com/boomker/rime-fast-xhup/blob/78ac2992f1aea90f44726851ad9baad54c885c44/lua/engword_append_space.lua

**Comment by ufo169** [comment]
> @ufo169 ，适用于英文输入方案的自动空格来了，参考: https://github.com/boomker/rime-fast-xhup/blob/78ac2992f1aea90f44726851ad9baad54c885c44/lua/engword_append_space.lua

好的，多谢先，之前我只是用简单的C语言结构修改了一下，指定符号顶屏带空格，也勉强实现。这段时间比较忙，等忙完这段时间，我测试一下
