### ISSUE TITLE
如何输出全角符号？

### ISSUE THREAD

**Issue by CarameowCookie** [boomker/rime-fast-xhup#52]
比如全角空格。

**Comment by boomker** [comment]
<img width="152" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/7d7edb6a-9fbe-48c4-9194-d93992d1dbf8">

`Alt+grave`， 呼出上面的方案选单，切换为全角，再输出符号。
我几乎没有全角输出符号的需求，不确定这样操作是否是符合预期。

**Comment by CarameowCookie** [comment]
![image](https://github.com/boomker/rime-fast-xhup/assets/74455347/7ecbaf52-d79f-403e-8548-0e0152a1bc2b)

来源：<https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E5%96%9A%E5%87%BA%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE%E7%9A%84%E5%BF%AB%E6%8D%B7%E9%8D%B5>

在我的环境（Windows）里，`Alt+grave` 没有任何反应，虽然这个组合键未被任何应用占用。

**Comment by CarameowCookie** [comment]
我已自行将其修改为 `Control+grave` 了。现在这个功能可以正常工作了。

**Comment by boomker** [comment]
新增了一个快捷切换配置选项的菜单功能
<img width="216" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/25bbdbca-fa9f-452d-a9af-37f2730e1e17">

　
<img width="228" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/571ad604-7f79-4fe3-b638-f42949d29380">

**Comment by CarameowCookie** [comment]
请问「编码区位样式」指的是什么呢？

**Comment by boomker** [comment]
> 请问「编码区位样式」指的是什么呢？

https://github.com/boomker/rime-fast-xhup/blob/e89a3c3178e30f527ea8b2532bdece05b78db710/flypy_xhfast.custom.yaml#L17
