### ISSUE TITLE
快捷指令更新后出现问题

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#53]
1、仍然出现了记忆情况
2、输出字母而不是输出内容

https://github.com/boomker/rime-fast-xhup/assets/158744320/af7b9f9d-6b87-4e52-9fc2-e102705934ca

**Comment by boomker** [comment]
你在 [这行](https://github.com/boomker/rime-fast-xhup/blob/e89a3c3178e30f527ea8b2532bdece05b78db710/lua/launcher_config.lua#L4) ，改成 `/` 开头的触发前缀试试。

我这边都是正常的。

**Comment by Hodwe** [comment]
是不是因为新加的这一串代码：
            or inputCode:match("^/j%l+")
导致只能使用/+字母
之前都好好的

**Comment by boomker** [comment]
和这个没有关系，触发前缀是可自由配置的，但是建议还是 `/`开头，避免影响到正常候选项。

**Comment by Hodwe** [comment]
/用作其他，我现在使用vvv作为触发词，但刚才的问题仍然存在，无法使用


https://github.com/boomker/rime-fast-xhup/assets/158744320/271e8c35-9ec9-43f0-8ffe-84d6a925f199

**Comment by boomker** [comment]
我知道问题所在了，临时解决：
注释掉这行：
https://github.com/boomker/rime-fast-xhup/blob/3a09c8ca28a0938e481bea793a2352f9755ba773/flypy_xhfast.custom.yaml#L41

或者：

<img width="215" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/ed2f3145-8c5d-445a-adc6-b4d064617e77">

**Comment by boomker** [comment]
<img width="802" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/bb859798-bdef-47c3-9410-67e063fe767b">

master 分支上的

**Comment by Hodwe** [comment]
我看的确实是master 分支上的，是17h以前的，没有更新

<img width="1254" alt="截屏2024-05-21 06 37 28" src="https://github.com/boomker/rime-fast-xhup/assets/158744320/226773f1-a48d-4ec7-bbe7-c34566f2af2c">

**Comment by Hodwe** [comment]
> 我知道问题所在了，临时解决： 注释掉这行：
> 
> https://github.com/boomker/rime-fast-xhup/blob/3a09c8ca28a0938e481bea793a2352f9755ba773/flypy_xhfast.custom.yaml#L41
> 
> 或者：
> 
> <img alt="image" width="215" src="https://private-user-images.githubusercontent.com/19751472/332023789-ed2f3145-8c5d-445a-adc6-b4d064617e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDUwMzAsIm5iZiI6MTcxNjI0NDczMCwicGF0aCI6Ii8xOTc1MTQ3Mi8zMzIwMjM3ODktZWQyZjMxNDUtOGM1ZC00NDVhLWFkYzYtYjRkMDY0NjE3ZTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDIyMzg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNWU4ZTJlOTI2ZTdlNDI4NjdlYjA2ZWVjMmMzMTc4NDgwNTI5MWMyYWVmY2RkMjllMWM1M2Q1NDAwNjc2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4a6w8YhBtuRIz4usgfIsj7vUac7S_9cEvaWz7pWi2c">

另外，这个lua我没有添加，可能是其他问题

**Comment by boomker** [comment]
@Hodwe 
把你的配置发我看下，我这边测试是没问题的， 可能是你其他的 `Lua` 造成了影响。

**Comment by Hodwe** [comment]
【快传】我给你发了 20...43.zip, 快来看看 https://www.alipan.com/t/pVtRtmSqmNbDR6swrdE5 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by boomker** [comment]
用 https://cowtransfer.com/ 上传文件分享。阿里云盘得下载客户端

**Comment by Hodwe** [comment]
https://github.com/Hodwe/12345/blob/main/2024.05.21-11.32.21.zip

**Comment by boomker** [comment]
@Hodwe 
我用了你的配置，没有问题

https://github.com/boomker/rime-fast-xhup/assets/19751472/721b252d-654a-4f2c-98a6-468b143007a0

**Comment by Hodwe** [comment]
我试了，我这个配置好像刚才的问题解决了，脱敏之后解决了，我一会再试试，看问题出在哪儿
另外，我刚才的方案有一个问题，就是输入vvma之后，就再也不能通过触发词触发界面，重新部署才可以

**Comment by Hodwe** [comment]
我试了，我这个配置好像刚才的问题解决了，脱敏之后解决了，我一会再试试，看问题出在哪儿
另外，我刚才的方案有一个问题，就是输入vvma之后，就再也不能通过触发词触发界面，重新部署才可以
