### ISSUE TITLE
将符号表中的摄氏度、华氏度改为正确的符号

### ISSUE THREAD

**Issue by CarameowCookie** [boomker/rime-fast-xhup#54]
使用 `/du` 所输出的摄氏度 / 华氏度符号，为「度」、「字母」两个字符的组合（而非一个 `℃` / `℉` 字符）。

在某些环境下，这会产生错误的排版（比如有些环境下 `°` 为全角字形，使得摄氏度 / 华氏度符号看起来不像单个字符）。

正确的符号是 `℃` / `℉`。

**Comment by boomker** [comment]
已修正
