### ISSUE TITLE
如何关闭直接英文输出？

### ISSUE THREAD

**Issue by CarameowCookie** [boomker/rime-fast-xhup#55]
不想在输入中文时组 **纯英文** 词汇（但是想要保留 **中英混合** 词汇），请问应该如何调整？

**Comment by boomker** [comment]
你的意思是候选项里不要出现 **纯英文** 的词条对吧
找到这个文件：[melt_eng.dict.yaml](https://github.com/boomker/rime-fast-xhup/blob/be8f24b42a3919233ccde7854d656dee2c7fd2a1/melt_eng.dict.yaml) 保留中英混合词库

最后在主配置文件了，注释掉[这三行](https://github.com/boomker/rime-fast-xhup/blob/be8f24b42a3919233ccde7854d656dee2c7fd2a1/flypy_xhfast.schema.yaml#L15-L17) 重新部署即可

**Comment by CarameowCookie** [comment]
这样操作过后，仍然有部分纯英文字母词汇（比如化学元素）

![image](https://github.com/boomker/rime-fast-xhup/assets/74455347/c396bf71-8736-4b87-b029-55fadf75da6d)

**Comment by boomker** [comment]
注释掉[这些行](https://github.com/boomker/rime-fast-xhup/blob/dc08ddd62de89f5a64790969de2b5b3ef419b4e5/opencc/others.txt#L604-L856)

**Comment by CarameowCookie** [comment]
请问这个词条属于哪个文件呢？我想把这些词条也禁用掉。

![image](https://github.com/boomker/rime-fast-xhup/assets/74455347/d715bab2-7d93-4d9f-be32-ed3d413ff5d6)

**Comment by boomker** [comment]
> 请问这个词条属于哪个文件呢？我想把这些词条也禁用掉。
> 
> ![image](https://private-user-images.githubusercontent.com/74455347/342099728-d715bab2-7d93-4d9f-be32-ed3d413ff5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTk3MjUsIm5iZiI6MTcxOTE5OTQyNSwicGF0aCI6Ii83NDQ1NTM0Ny8zNDIwOTk3MjgtZDcxNWJhYjItN2Q5My00ZDlmLWJlMzItZWQzZDQxM2ZmNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NmFmODc1YzNhNWZhNjZlOGU3MDljMTkyOGJmYmU2NmJmZmRkZDU2NTA3MWI4OTY5NmQyOWVlMjRiYWRkMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Sfz2nyKVKhcbr5fHPDRK_JF0HH4ogj3Rjqt0sr8ytM)

在`custom_phrase.txt` 里，找一个全文搜索的工具，就能搜到
