### ISSUE TITLE
如何修改码表？

### ISSUE THREAD

**Issue by joeywayn** [boomker/rime-fast-xhup#56]
如何修改部分底层码表？
比如我想将 B 键上的韵母 in 换到 Q 键上，然后再将Q键上的韵母 iu 换到 T 键上，总之就是需要更换多个键位。

**Comment by boomker** [comment]
如果是几个韵母的键位变换，可以用下面的方式
通过拼写运算实现：
      - derive/^(.)q$/$1Q/
      - derive/^(.)b$/$1q/
      - derive/^(.)Q$/$1t/

如果是有许多个这样的键位变换，还是直接改[字表词典文件](https://github.com/boomker/rime-fast-xhup/blob/be8f24b42a3919233ccde7854d656dee2c7fd2a1/cn_dicts/flypy_chars.dict.yaml)， 批量替换可能需要一些脚本能力

**Comment by joeywayn** [comment]
> 如果是几个韵母的键位变换，可以用下面的方式 通过拼写运算实现： - derive/^(.)q$/$1Q/ - derive/^(.)b$/$1q/ - derive/^(.)Q$/$1t/
> 
> 如果是有许多个这样的键位变换，还是直接改[字表词典文件](https://github.com/boomker/rime-fast-xhup/blob/be8f24b42a3919233ccde7854d656dee2c7fd2a1/cn_dicts/flypy_chars.dict.yaml)， 批量替换可能需要一些脚本能力
 
替换了 字表字典 后，那么对应的词库也需要再来一次替换吗？
还有一个疑惑，就是能不能直接改写码表，如 'in' : 'x' ，'ing': 'f'吗？然后相对应的字典文件就会自动转换了（我在手心输入法自定义的双拼方案，然后鹤形辅助码也能对应得上，我想能不能以这种相对简单的方式来替换

**Comment by boomker** [comment]
那就推荐写运算规则
- derive/^(.)q$/$1Q/
- derive/^(.)b$/$1q/
- derive/^(.)Q$/$1t/
类似这种，但是如果替换的比较多，有交叉回环的替换规则的话， 可能不生效，我没试过，不确定，你试试看。

**Comment by joeywayn** [comment]
> 那就推荐写运算规则
> 
> * derive/^(.)q$/$1Q/
> * derive/^(.)b$/$1q/
> * derive/^(.)Q$/$1t/
>   类似这种，但是如果替换的比较多，有交叉回环的替换规则的话， 可能不生效，我没试过，不确定，你试试看。

最后再叨扰一下，[rime-fast-xhup](https://github.com/boomker/rime-fast-xhup/tree/master)/[scripts](https://github.com/boomker/rime-fast-xhup/tree/master/scripts)
/flypy_dict_generator_new.py ，在上面这个文件86行开始，应该可以直接更改码表，然后通过163行的代码可以批量转换，但是尝试操作了一下，没有生效，如果您方便的话，还请帮忙看一下能否实现。十分感谢！

**Comment by boomker** [comment]
改`flypy_dict_generator_new.py`是可以，但是你得用脚本重新生成字表和词库文件才行。
