### ISSUE TITLE
词库 `cn_dicts/others` 启用后，无法编译

### ISSUE THREAD

**Issue by CarameowCookie** [boomker/rime-fast-xhup#57]
查看了日志，无法编译的原因是 `cn_dicts/others.dict.yaml` 这个文件不存在。

**Comment by boomker** [comment]
没有这个 others.dict.yaml文件，就不要启用嘛。
这个 others 是预留给到用户自己私有词典的。

`cn_dicts/others` 这里面的一些词典文件是包含简繁和形码编码的，而且体积小。有这种需求的可以启用，一般不用管。
