### ISSUE TITLE
 候选栏问题

### ISSUE THREAD

**Issue by joeywayn** [boomker/rime-fast-xhup#59]
![image](https://github.com/boomker/rime-fast-xhup/assets/170803046/aa423177-2b9f-4460-9e55-28ac8dad18fb)
这里已经设置了横向，为什么部署后还是竖着的？

**Comment by boomker** [comment]
小狼毫我没测试过，鼠须管改成截图的样子是生效的。
你可能得改这个地方：
https://github.com/boomker/rime-fast-xhup/blob/e51b276a56ab2908029fc3db15b97692479ad0ad/weasel.yaml#L55
