### ISSUE TITLE
punctuator无法正常输入

### ISSUE THREAD

**Issue by harry7756** [boomker/rime-fast-xhup#6]
系统:  Mac OS 13.6
鼠须管 0.16.2

使用您最新的方案后，punctuator无论是在全角／半角都无法按照 default 默认的输入。

比如系统设置如下:
---
"|": ["·", "｜", "§", "¦"]
...

但是我输入“|“，在半角状态下得到“·“，在全角状态下得到“|“。
无法如系统设定的，跳出选择页让我选择。

**Comment by boomker** [comment]
对于符号输入，我个人比较倾向直接上屏，不显示候选菜单，所以就设定直接上屏了
最新配置现在已经改回来，你拉取最新`commit`试试
