### ISSUE TITLE
快捷指令功能的扩展与 Bug

### ISSUE THREAD

**Issue by Anber55** [boomker/rime-fast-xhup#60]
反馈几个问题，有的可能不是：
1、如图所示，快捷指令设置排序的数时，是不是最多到9，到10时会将10显示出来⬇️
<img width="162" alt="截屏2024-06-05 08 11 22" src="https://github.com/boomker/rime-fast-xhup/assets/117334130/5b72942e-b060-4c73-88d0-677181ab5e88">
2、如视频所示，如果给终端命令前加上字母方便输出时，会导致所有的快捷指令不起作用，直接输出字符而不是命令，其他的指令前面加字母都是正常的⬇️
3、如视频所示，仍然会出现【记忆】情况，影响输入⬇️
https://github.com/boomker/rime-fast-xhup/assets/117334130/08a28923-b691-4441-813d-f51b269f36f7

**Comment by Anber55** [comment]
补充一下，在电脑端的：终端、路径、书签可以直接执行命令，在iOS上则处于无用状态，能否实现电脑端直接运行相应命令，而在iOS端能够起一个snippets的作用，直接输出相应的文本

**Comment by boomker** [comment]
1. 这个 bug 已经解决，会在稍晚一些时间推送更新
2. 加上字母是可以正常执行命令的，我这边测试正常(通过字母来选中对应菜单)。
3. 出现【记忆】情况，我这边测下来发现在翻页后会这样。
<img width="331" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/f12cefe4-acfd-4331-896b-69807b643bf3">

在按下上下方向键后，是如何退出输入面板菜单的？ 如果是在候选菜单第一页 按下`Esc` 键是不会有记忆情况的。

4. > iOS端能够起一个snippets的作用

这个可以做，只要脚本能识别到是 `iOS` 设备就行。

**Comment by Anber55** [comment]
2、其他的指令前面加字母进行选中是完全OK的，我这边只有终端的前面加字母才会导致直接输出文本的问题
		["i终端8"] = {
			["action"] = "exec",
			["items"] = {

3、情况二：进入子菜单，不进行输出，也会存在记忆情况
这个就是通过ESC退出的，但仍然有记忆功能
https://github.com/boomker/rime-fast-xhup/assets/117334130/54c4a7b5-1e67-451c-aa9e-b3f6d727b74e

**Comment by boomker** [comment]
「 终端命令」组里菜单前面加上字母，也是正常可以执行对应的命令的。
你检查一下这行配置是不是放在靠前的位置：
https://github.com/boomker/rime-fast-xhup/blob/823263ec4d8aeb2d9ed95cb0cc79ba33750d7f04/flypy_xhfast.schema.yaml#L39

把这行配置放在 `processor` 节点下第一个试试看。

**Comment by Anber55** [comment]
1、放在第一行还是不行，还是直接输出文本而不是命令，奇怪
<img width="741" alt="截屏2024-06-05 13 34 02" src="https://github.com/boomker/rime-fast-xhup/assets/117334130/34e4ac92-291a-4c9d-ba01-1e1a76bb121b">

2、佬帮我看看快捷指令仍然有记忆，这个能不能消除记忆

3、下面这两行代码为什么添加到快捷指令的终端中会导致打不出字
				["小企鹅部署7"] = "/Library/Input\ Methods/Fcitx5.app/Contents/bin/fcitx5-curl /config/addon/rime/deploy -X POST -d '{}'",
				["小企鹅同步8"] = "/Library/Input\ Methods/Fcitx5.app/Contents/bin/fcitx5-curl /config/addon/rime/sync -X POST -d '{}'",

**Comment by Anber55** [comment]
第一个问题我知道原因了
正确：["F刷新DNS缓存6"] = "dscacheutil -flushcache",
错误：["F 刷新DNS缓存6"] = "dscacheutil -flushcache",
前面的字母和后面的名称之间不能隔一个空格，隔一个空格就会导致所有的错误

但是其他菜单都是可以隔空格的，大佬能不能修复一下这个问题

**Comment by Anber55** [comment]
第三个问题大概也找出问题了，是由于符号\导致的，但是去掉符号\命令运行又是错误的，不知道怎么设置

**Comment by boomker** [comment]
> 前面的字母和后面的名称之间不能隔一个空格，隔一个空格就会导致所有的错误

我的建议是，不要在配置里添加空格，有其他脚本会自动添加空格的，加了空格脚本会自动移除的，
不然没法判断是手动添加的还是脚本程序添加的。我自己的没加空格，效果如下：
<img width="187" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/b2dca863-014d-42cb-9448-db1735a9b090">

 下面这个脚本是用来自动添加空格的：
https://github.com/boomker/rime-fast-xhup/blob/823263ec4d8aeb2d9ed95cb0cc79ba33750d7f04/flypy_xhfast.custom.yaml#L43-L44

**Comment by Anber55** [comment]
1、我没有用这个添加空格的lua，那我用一下
2、我问QQ群的小企鹅作者给我的

**Comment by Anber55** [comment]
自动添加空格是这个lua是吗？
word_append_space.lua

**Comment by Anber55** [comment]
这个lua对应的schema和rime.lua怎么设置，怎么没看见

**Comment by boomker** [comment]
<img width="803" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/db40763f-b0c5-4cab-b134-2fe65fd0192b">


<img width="724" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/eafae6e4-70f6-4d38-875d-6e7c07c36ac4">

**Comment by Anber55** [comment]
我先不加了，有点乱，其实前面的菜单。例如：路径、书签、卡号等都加了空格没事，就是最后的终端不行，先不加了，谢谢了

**Comment by boomker** [comment]
> 第三个问题大概也找出问题了，是由于符号\导致的，但是去掉符号\命令运行又是错误的，不知道怎么设置

我这边测试下来，在鼠须管里是可以正常执行的， 在小企鹅里会卡死。
注意的是：去掉空格。
<img width="1339" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/cb862891-8a4b-4a55-a5e2-afcb1ee87ad1">

**Comment by Anber55** [comment]
命令是这样运行的吗：
/Library/Input Methods/Fcitx5.app/Contents/bin/fcitx5-curl /config/addon/rime/deploy -X POST -d '{}'

报错：
zsh: no such file or directory: /Library/Input

**Comment by boomker** [comment]
> 命令是这样运行的吗： /Library/Input Methods/Fcitx5.app/Contents/bin/fcitx5-curl /config/addon/rime/deploy -X POST -d '{}'
> 
> 报错： zsh: no such file or directory: /Library/Input

在终端执行下这行看下：
```bash
ll "/Library/Input Methods/Fcitx5.app/Contents/bin/fcitx5-curl"
```

**Comment by Anber55** [comment]
-rwxr-xr-x@ 1 root  wheel   337B  6  4 19:29 /Library/Input Methods/Fcitx5.app/Contents/bin/fcitx5-curl

**Comment by Anber55** [comment]
["小企鹅部署7"] = "/Library/Input\ Methods/Fcitx5.app/Contents/bin/fcitx5-curl /config/addon/rime/deploy -X POST -d '{}'",
["小企鹅同步8"] = "/Library/Input\ Methods/Fcitx5.app/Contents/bin/fcitx5-curl /config/addon/rime/sync -X POST -d '{}'",
以上仍然会导致无法输入字
去掉\无法运行命令

**Comment by boomker** [comment]
除了这两条指令，其他都正常吗？
没法复现你的情况，可能是你那边其他`Lua` 给影响了。
直接用我的方案，测试一下。

**Comment by Anber55** [comment]
可以正常运行了，但是一旦用“小企鹅部署和同步”，Mac就会立马被卡死，必须关机或重启才能解决，而且关机或重启的过程中都得卡十几次
<img width="128" alt="截屏2024-06-05 20 11 31" src="https://github.com/boomker/rime-fast-xhup/assets/117334130/bd15dd31-6f5a-4824-92b7-6c054358535c">

**Comment by Anber55** [comment]
终端运行刚才的部署指令正常，利用快捷指令不正常

**Comment by Anber55** [comment]
再反馈几个问题：
1、快捷指令记忆的情况我这一直在复现，大佬看能不能解决
2、在Mac小企鹅上，快捷指令可以正常工作，但是快捷打开APP无法工作
3、不用中英文之间添加空格的lua的用户，能否实现在终端菜单中的前面使用字母+空格
主要是其他菜单都可以，只有终端不可以，就很奇怪

**Comment by boomker** [comment]
我又更新了一版
1. 这个应该是解决了，你再测一下
2. 这个得问问 小企鹅那边的情况
3. 这个已经实现了。

**Comment by Anber55** [comment]
我拉取了最新的launcher.lua，但是部署后无法打字

**Comment by boomker** [comment]
> 我拉取了最新的launcher.lua，但是部署后无法打字

不可能吧，你用我的方案配置试试看呢，你把其他` Lua `给线禁用掉看看

**Comment by Anber55** [comment]
奇怪，我把所有的lua都禁用了，然后换成新的launcher.lua立马不能打字，还原为旧的launcher.lua里面又可以打字，太奇怪了

**Comment by boomker** [comment]
你看下有没有错误日志，看看是否可以发现线索。你把触发前缀换成默认的呢，也都试试吧。

**Comment by Anber55** [comment]
明白了，谢谢，现在可以了

**Comment by Anber55** [comment]
大佬抽空看看最后一个iOS的功能能不能实现，感谢
在电脑端的：终端、路径、书签可以直接执行命令，在iOS上则处于无用状态，能否实现电脑端直接运行相应命令，而在iOS端能够起一个snippets的作用，直接输出相应的文本

**Comment by boomker** [comment]
> 大佬抽空看看最后一个iOS的功能能不能实现，感谢 在电脑端的：终端、路径、书签可以直接执行命令，在iOS上则处于无用状态，能否实现电脑端直接运行相应命令，而在iOS端能够起一个snippets的作用，直接输出相应的文本

这两天空了，我尝试支持一下，只能麻烦你协助我多多测试了，我没 ios 设备

**Comment by Anber55** [comment]
好的，没问题，感谢
