### ISSUE TITLE
如何去掉「成语短语」候选

### ISSUE THREAD

**Issue by queyuewutong** [boomker/rime-fast-xhup#61]
大佬您好，我现在用的是小鹤双拼，我遇到的问题是比如我打个今天，jbtm，会出现候选词金榜题名，这个词一直占据首位，还有我打狗哥，出现的公子哥也是一直占据首位，这个现象不会随词频调整，我把超级简拼注释掉以后，好像也不起作用，您能看看怎们回事儿么？

**Comment by boomker** [comment]
注释以下几行：
https://github.com/boomker/rime-fast-xhup/blob/823263ec4d8aeb2d9ed95cb0cc79ba33750d7f04/flypy_xhfast.schema.yaml#L159-L166

 和超级简拼没有关系的，这个是之前没有开启超级简拼时手动弄的一个词库，为了能快捷输入成语诗词短句。

**Comment by queyuewutong** [comment]
> 注释以下几行：
> 
> https://github.com/boomker/rime-fast-xhup/blob/823263ec4d8aeb2d9ed95cb0cc79ba33750d7f04/flypy_xhfast.schema.yaml#L159-L166
> 
> 和超级简拼没有关系的，这个是之前没有开启超级简拼时手动弄的一个词库，为了能快捷输入成语诗词短句。

这个注释写到flypy_xhfast.custom不管用么？必须在flypy_xhfast.schema里面注释掉么？

**Comment by boomker** [comment]
你可以把这段剪切到 ‘custom’ 配置里
