### ISSUE TITLE
输入卡顿、候选框跳动与闪现

### ISSUE THREAD

**Issue by Well-key** [boomker/rime-fast-xhup#63]
系统环境：Win11 22H2 
启用的大词库有：
  - cn_dicts/flypy_wuhgit       # from github.com/wuhgit
  - cn_dicts/flypy_tencent      # 腾讯词向量(大词库, 部署时间较长)
输入卡顿：实际键盘卡顿感感受更强。
候选框跳动与闪现：目前在Firefox上最明显。
![卡顿](https://github.com/boomker/rime-fast-xhup/assets/78063838/d0fe3616-1515-4d92-9258-4f6c928212d5)

附资源占用情况。
![系统占用](https://github.com/boomker/rime-fast-xhup/assets/78063838/b56584dd-5235-48fc-ba16-f22315586101)

**Comment by boomker** [comment]
1. 检查你的小狼毫是否是最新的版本，记得最新版本是支持到了64位的。
2. 候选框跳动这个问题，可能和 GitHub 网站 Firefox 浏览器有关系。
这个问题我在 Edge 浏览器也同样是 GitHub 上其他页面遇到过， 你可以用系统自带微软输入法测试是否有同样的问题。

**Comment by Well-key** [comment]
感谢，已更新新版本x64小狼毫。
候选框跳动已不复现，卡顿也有改善。

**Comment by Well-key** [comment]
已更新新版本x64小狼毫。
候选框跳动已不复现，卡顿情况稍有改善。
感谢，
