### ISSUE TITLE
Windows 下 `shift + '` 上屏 ``“”“”`` 或 """"

### ISSUE THREAD

**Issue by caox-dev** [boomker/rime-fast-xhup#64]
我下载了此方案，其他都合适，只有这一个问题：`shift + '` 上屏 ``“”“”`` 或 ``""""`` ，双引号出现两对，单引号是合适的，麻烦作者大神给看一下是啥原因呢！

**Comment by boomker** [comment]
把这行注释掉或删掉
https://github.com/boomker/rime-fast-xhup/blob/0e70a85a8e4d4388665f22df4c7c5bbba3ac4470/flypy_xhfast.schema.yaml#L41
