### ISSUE TITLE
中英文切换问题

### ISSUE THREAD

**Issue by V1067** [boomker/rime-fast-xhup#66]
请问 MacOS 如何快速切换呢？

**Comment by boomker** [comment]
切换到英文状态，按 右 `Shift`， 可以在配置里改键

切换到英文方案，按「Option+`」 进入「方案选单」，选中 'Easy English'切换到系统 ABC 输入法，按`Ctrl+space`

**Comment by V1067** [comment]
感谢大佬，真详细👍

**Comment by V1067** [comment]
> 切换到英文状态，按 右 `Shift`， 可以在配置里改键
> 
> 
> 
> 切换到英文方案，按「Option+`」 进入「方案选单」，选中 'Easy English'
> 
> 
> 
> 切换到系统 ABC 输入法，按`Ctrl+space`

感谢大佬，真详细👍
