### ISSUE TITLE
小狼毫，无法持久保存由 `/so` 菜单所设置的状态

### ISSUE THREAD

**Issue by CarameowCookie** [boomker/rime-fast-xhup#67]
操作系统：Windows 10 IoT Enterprise LTSC 2021
操作系统版本号：21H2（19044.4529）

输入法引擎：小狼毫 Stable
输入法版本号：0.16.1.0

在皮肤样式跟随系统深浅色模式切换之后，由 `/so` 所设置的状态（如 字体大小）恢复了默认。

**Comment by boomker** [comment]
由 `/so` 所设置的状态就只是临时生效，不会写入配置文件，
系统深浅色模式切换后会重新读取配置文件，由于配置文件没有改变，所以就会恢复默认。
