### ISSUE TITLE
macOS 12.7.6  鼠须管导入配置部署后不能输入中文

### ISSUE THREAD

**Issue by housemlm** [boomker/rime-fast-xhup#68]
鼠须管的版本应该是0.16.2，将仓库里的文件clone后全部拷贝到rime文件夹下，重新部署完成后，无法输入中文，能显示输入窗，没有选字的窗口，只能输入英文，可以调出配置菜单，已经选择飞鹤快拼模式。已经尝试重启，退出登陆，重新安装鼠须管等方式。还是不行。

**Comment by boomker** [comment]
鼠须管不支持  MacOS 13 以下的系统了
