### ISSUE TITLE
这个候选字的编号怎么是圆圈的

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#69]
![image](https://github.com/user-attachments/assets/9df70100-edbb-4526-9e30-1540818c794c)

不会改，是新版的ui还是可以配置的？

**Comment by boomker** [comment]
<img width="785" alt="image" src="https://github.com/user-attachments/assets/52a967d3-215e-423f-a6d4-89661af67b3b">

**Comment by calmwaves111** [comment]
呀没注意到这行，谢谢回复
