### ISSUE TITLE
日期的 lua 能否更改一下

### ISSUE THREAD

**Issue by edison0808** [boomker/rime-fast-xhup#7]
从快手循迹过来的，大佬目前配置的日期 lua 看起来是没有空格的，但实际年月日中间多出了一个空格，不太符合日常习惯，能否调整一下？谢谢

**Comment by boomker** [comment]
不会吧，有空格的呀
<img width="307" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/5ccf2ad9-7677-40e5-81e1-9aae19cc8b43">
<img width="318" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/baa566f5-3aa7-49fe-8536-67c921cbad91">

**Comment by edison0808** [comment]
我的意思是在 lua 文件里面显示是没有空格 但实际出来效果有空格  个人是希望能把空格去掉 
![image](https://github.com/boomker/rime-fast-xhup/assets/131497804/2ced7b03-1cc8-499c-8041-17430a19330f)

PS:1.关于直接引用辅助码的设置 是直接把flypy_xhfast.schema里面的配置注销掉吗？目前直接引用是否只对单字有效，对词组无效？
![image](https://github.com/boomker/rime-fast-xhup/assets/131497804/2d6fd4b5-c0c1-4b83-9d91-d97bba06f0d7)
但我看flypy_xhfast.custom里面又有不同的提法， 具体怎样才是正确的呢？
![image](https://github.com/boomker/rime-fast-xhup/assets/131497804/7fdc50a1-5224-4664-9165-f5c98ed7d1de)
2.说明里面的组件模式有笔误，应为  oq
![image](https://github.com/boomker/rime-fast-xhup/assets/131497804/6427215f-f331-4b0d-ac59-5a36b5be64d2)

**Comment by boomker** [comment]
> 希望能把空格去掉
---
最新代码已经去掉
> 关于直接引用辅助码的设置 是直接把flypy_xhfast.schema里面的配置注销掉吗？目前直接引用是否只对单字有效，对词组无效？
---
使用`flypy_xhfast.custom`里配置，将注释放开。若想对词组能使用直接辅助码，最好是词库里每个词条都要有形码的编码，貌似直接辅助码有时候体验不太好，我默认就没启用。

**Comment by edison0808** [comment]
> > 希望能把空格去掉
> 
> 最新代码已经去掉
> 
> > 关于直接引用辅助码的设置 是直接把flypy_xhfast.schema里面的配置注销掉吗？目前直接引用是否只对单字有效，对词组无效？
> 
> 使用`flypy_xhfast.custom`里配置，将注释放开。若想对词组能使用直接辅助码，最好是词库里每个词条都要有形码的编码，貌似直接辅助码有时候体验不太好，我默认就没启用。

已经用上了  感谢大佬 的确直接辅助码有时候会失灵或者混乱 不知道流星追方案月是不是借用了其他插件才实现的

**Comment by edison0808** [comment]
大佬我又来打扰了，我在iOS和win上分别部署了方案，目前发现人名之类的非词库词组在iOS的仓app上面只要输入一次就能够自动记住，但win上面的却没法记住，不知道是个性问题还是共性问题？另外还有idiom里面的成语简写，翘舌的编码规则不统一，有的sh用了u，有的用了s

**Comment by boomker** [comment]
流星追月方案，我有参考过，应该没有用其他插件。可能是他用了特殊的配置，看他从单字到词组都有 schema 方案，然后在主方案里引用。后面我详细研究后，看看能不能借鉴过来。
win平台我没测过，我没考虑过多平台
idiom里面的成语简写编码规则不统一，这个确实有，我后面再改吧

**Comment by edison0808** [comment]
>  win平台我没测过，我没考虑过多平台
这样啊，大佬有空的时候不知道能不能帮忙看看 win 的（如果大佬有用 win 设备的话）？感谢

**Comment by boomker** [comment]
没有 win 设备，空了装台虚拟机测一下

**Comment by edison0808** [comment]
> 没有 win 设备，空了装台虚拟机测一下

好的 辛苦大佬了

**Comment by edison0808** [comment]
> 大佬我又来打扰了，我在iOS和win上分别部署了方案，目前发现人名之类的非词库词组在iOS的仓app上面只要输入一次就能够自动记住，但win上面的却没法记住，不知道是个性问题还是共性问题？

目前发现的一些情况，供大佬参考:
1.如果手动输入的为词库内没有的姓名，如李散斯， Rime 无法记住，可以通过 [ 引导手工造词的方式进入字典（`的引导方式无效），后续可以直接双拼输入；
2.如手工输入的人名前两个为词库原有词组，第三个字为首次输入是手动选择的，该词条可以被记住，后续可以双拼输入，如 lojpuf 可得罗杰申；
3.如果是词库内原有的两个以上词组组合上屏，上屏记录同样可以被记住，后续可以连打词组的双拼直接上屏，无须逐个选择。

**Comment by boomker** [comment]
好的，感谢反馈。
'\`'键引导手动造词，需要自己改配置的，我没用这个键，这个键用来造 英文生词，在英文生词末尾输入'`'键来触发

**Comment by edison0808** [comment]
> 好的，感谢反馈。 '`'键引导手动造词，需要自己改配置的，我没用这个键，这个键用来造 英文生词，在英文生词末尾输入'`'键来触发 现在 大多数时候一次上屏就能记住生词，少数情况通过逐个选择的词组会没法记住, 后面我写个 lua 来做分词实现

好的，我看  readme 里面有写'`'键引导手动造词，以为是方案默认的功能。期待大佬早日更新 lua， 感谢！

**Comment by edison0808** [comment]
大佬 请问一下方案如何可以输入“、”号？

**Comment by boomker** [comment]
> 大佬 请问一下方案如何可以输入“、”号？

按`\`, 如图
<img width="158" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/50b53773-6a47-400c-98c5-f2a600722eed">

**Comment by edison0808** [comment]
大佬，想问下方案是不是不能双引号自动上屏？另外中文的双引号我好像打不出来另一边，只有“  没有”

**Comment by boomker** [comment]
更新修复了，之前我都用英文单双引号
有点小的变化：
按`'`会输出双引号`“`；按`"`会输出单引号`‘`
如果不习惯，可以把下面的配置注释掉
<img width="694" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/3149ed9a-3f1a-466f-aa73-bf49c8db768e">

**Comment by edison0808** [comment]
太好了，是否只更新主配置方案就行呢？顺便想问下大佬此前提的win上自动记录生词的lua有更新了吗

**Comment by boomker** [comment]
> 太好了，是否只更新主配置方案就行呢？顺便想问下大佬此前提的win上自动记录生词的lua有更新了吗

---
对的，只用更新主方案就行。记录生词的那个优先级比较低，有空再弄。

**Comment by edison0808** [comment]
大佬，貌似我下载了最新的主方案也一样不行…

**Comment by boomker** [comment]
怎么会呢？ 你「重新部署」了吗？
我在 Mac 上是可以的
![iShot_2023-09-13_18 26 57](https://github.com/boomker/rime-fast-xhup/assets/19751472/eacc442a-87f1-4833-9599-27333022e3af)

**Comment by edison0808** [comment]
部署了  也试过删除build文件再部署 也是一样不行 可能还是win的系统差异吧

**Comment by edison0808** [comment]
现在版本的librime用的是1.8.5  应该已经是最新的了吧？

**Comment by edison0808** [comment]
那应该不是 librime 版本的原因,估计就是 win 和 mac 对符号的处理不一样

**Comment by edison0808** [comment]
大佬方便说一下方案里面有哪些文件或者地方是有对标点符号做了设置的吗？我研究一下是否可以拿其他能上屏的方案来替换

**Comment by boomker** [comment]
在 lua 里有个地方
https://github.com/boomker/rime-fast-xhup/blob/e51b9d485789910b899ffe0e688ee559ae43a21f/lua/cold_word_drop.lua#L166C1-L166C1

**Comment by edison0808** [comment]
略复杂  没看明白 😅不过还是感谢大佬 我拿了雾凇拼音的 lua 复制过来 替换了原有相同的部分 然后就 OK 了～另外想问下大佬，有些繁体字如果不想被过滤掉应该怎么设置？

**Comment by edison0808** [comment]
略复杂  没看明白 😅不过还是感谢大佬 我拿了雾凇拼音的 lua 复制过来 替换了原有相同的部分 然后就 OK 了～另外想问下大佬，有些繁体字如果不想被过滤掉应该怎么设置？

**Comment by boomker** [comment]
额嗯，是略显复杂点了，有空优化一波。雾凇那边是把我这个拆成了几个文件，看起来会轻松一点
繁体字不被过滤掉？你是日常就开启了繁体字输出的设置是吗。
如果是不想过滤某一单个繁体字，不放到过滤列表文件里就好。还是不太明白你具体的需求，可以描述一下在什么场景下不过滤繁体字

**Comment by edison0808** [comment]
日常主要输入的还是简体字，我的主要场景还是一些人名的输入 比如鑑、啟、霑，类似这些可能会被纳入繁体字的字，貌似打不出来

**Comment by edison0808** [comment]
> 额嗯，是略显复杂点了，有空优化一波。雾凇那边是把我这个拆成了几个文件，看起来会轻松一点 繁体字不被过滤掉？你是日常就开启了繁体字输出的设置是吗。 如果是不想过滤某一单个繁体字，不放到过滤列表文件里就好。还是不太明白你具体的需求，可以描述一下在什么场景下不过滤繁体字

大佬优化的时候如果有可能建议可以兼顾一下  win 的使用，我目前发现 iOS 、iPad和 win 上出来的效果真的会不同，比如自动记录上屏词组、“”的快捷上屏， iOS 上是能记录的，“”上屏后输入光标也是在标点符号中间，但 win 就不能记录，“”上屏后输入光标在冒号后面。个人觉得可能是 lua 的原因？

**Comment by boomker** [comment]
保留一些繁体字的话，需要手动把 OpenCC 中转为简化字的映射给删掉，比如，把下面第3062行给删掉
opencc/TSCharacters.txt
3062:霑 沾
如果是用雾凇的字表的话，启用「大字表」即可。

----
> OS 上是能记录的，“”上屏后输入光标也是在标点符号中间，但 win 就不能记录，“”上屏后输入光标在冒号后面

这个没太懂什么意思，有截图 gif 可以演示吗

**Comment by edison0808** [comment]
不太会用 gif 截图，我简单截个图吧:
win上面是这样，要手动调整光标
![image](https://github.com/boomker/rime-fast-xhup/assets/131497804/9f7dce26-45e7-4274-9504-0fe85efcd890)
 iOS 上是这样，可以直接输入引号里面的内容
![image](https://github.com/boomker/rime-fast-xhup/assets/131497804/a120b3ac-862d-4829-bbac-70244a101f9c)

**Comment by boomker** [comment]
这个功能是自动成对符号，并且光标在成对符号中间，在我这个方案里还没支持了，在 Mac 也是不行的。
iOS 能有这样的效果，可能是 iOS 系统上的其他机制实现的。

**Comment by edison0808** [comment]
喔喔  照你这么说 那有可能是仓输入法 app自带的什么机制
