### ISSUE TITLE
【提议】合并 custom yaml 文件入 schema yaml 

### ISSUE THREAD

**Issue by zhengpd** [boomker/rime-fast-xhup#71]
flypy_xhfast.custom.yaml 包含了很多内容，在用户只需要自定义三两个配置项的时候，不利于快速分辨在 rime-fast-xhup 的基础上做了哪些修改。建议把 flypy_xhfast.custom.yaml 合并入 flypy_xhfast.schema.yaml，让用户可以使用 flypy_xhfast.custom.yaml 专门维护少数自定义配置

**Comment by boomker** [comment]
之前合入过一部分内容到主配置(`flypy_xhfast.schema.yaml`)里了，现有的`custom` 配置是留给用户可以自定义的，
大部分情况下，也只需要改`custom`配置 就行了。
主要是本方案包含的功能较多，可以自由配置的地方也较多，导致`custom` 看起来内容很多。
你看看，有哪些内容可以合入到主配置里，我到时候看情况合入。
