### ISSUE TITLE
快捷短语有可能实现指定光标位置吗

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#72]
![image](https://github.com/user-attachments/assets/f143507b-2b72-41d2-a6a2-fbd1d667758a)

就比如这个，我想在打字的时候，输入之后自动把光标移动到括号()中间，不知道能不能用一个类似<cursor>这样的占位符，或者允许我模拟一下按左箭头？

我就这么问一下，要是实在实现不了的话，那直接关掉这个 issue 也就罢啦！

**Comment by boomker** [comment]
理论上是可以做到的，目前方案里符号配对，就有光标左移的功能，但是仅限 macOS。
这类功能，也可以用第三方 `snippet` 代码片段应用实现，比如：
<img width="279" alt="image" src="https://github.com/user-attachments/assets/725864f2-b7ec-4161-bf07-d746d6f474f4">

这个是 macOS 上快捷启动应用`Raycast` 自带的功能

**Comment by calmwaves111** [comment]
emmm我是win10（苦笑

其实也想过用其他的snippet应用，但是和小狼毫输入法的兼容一直不怎么好，因为小狼毫打字的时候会先打出一个空格，如果把inline_preedit改成false又会有其他奇奇怪怪的冲突，而且我也不习惯

所以希望小狼毫自己能有这个功能

**Comment by trevim99** [comment]
@boomker , @calmwaves111 大佬們好，

我最近有試著把 飛鶴快拼+ AHK2 初步測試是可行的。😅
也許修改 pair_symbols.lua 即有機會實現 在 windows 符號補全及移動光標。
（#用lua 脚本呼叫 ahk2 脚本🤣）

🙏🙏🙏

1.ahk2脚本（move_cursor.ahk2）
可用/jk前綴觸發及向左移動光標。

2.如果自動補全的lua脚本
（pair_symbols.lua）也能觸發
move_cursor.ahk2，也許就能在
windows符號補全及移動光標了（？）


<img width="1080" alt="补全" src="https://github.com/user-attachments/assets/160737df-26dc-46a9-b4e4-d7528abc2f2f">

**Comment by boomker** [comment]
> 我最近有試著把 飛鶴快拼+ AHK2 初步測試是可行的

---

太棒了，测试可行的话，可以将源码和编译后的 exe 程序，提个 PR

**Comment by trevim99** [comment]
> move_cursor.ahk2

boomker 大佬， 我對  lua 一竅不通 🤣😅
我還沒PR過 🤣😅
（想測試的飛鶴快拼友可參見圖片，要改那些地方，我都標出來了😂）
move_cursor.ahk2 的源碼如下： （如格式跑掉，可參見圖片）

···
#Requires AutoHotkey v2
#SingleInstance Force
;搭配 飛鶴快拼方案的光標移位。
;
;2024-10-08 
;
	Send "{Left}"
···

**Comment by boomker** [comment]
也可以发文件在这里，`AHk` 源码和它的打包成 exe 的程序文件

**Comment by trevim99** [comment]
@boomker ，@calmwaves111  大佬們好，

一，初步測試，Windows-飛鶴快拼 + ahk 2 可以符號補全及光標移位了 😅🤣
二，

🙏pair_symbols.lua 要修改：
1.function moveCursorToLeft(env)
增加 move_cursor.ahk2 的 内容

2. function P.func(key, env)
裏的 if 條件式疑似使得 無法呼叫 function moveCursorToLeft(env)
（我打 檔案裏用？？？ 表示（有2處））


三，我把ahk源碼及待修改的pair_symbols.lua檔案傳上這裏， github 我還不太熟悉，見諒。 😂
(副档名加上 txt 才传得上来）


[待修改pair_symbols.lua.txt](https://github.com/user-attachments/files/17291341/pair_symbols.lua.txt)

[move_cursor.ahk2.txt](https://github.com/user-attachments/files/17291346/move_cursor.ahk2.txt)


)
四，再次謝謝 boomker 大佬， 飛鶴快拼 很好用，謝謝🙏🙏🙏


![image](https://github.com/user-attachments/assets/dfb2927d-5442-4dc1-b87a-128c7983ce33)

**Comment by boomker** [comment]
ahk源码得需要用户事先安装`AutoHotKey`环境，你那边打包成 exe ，其他人用起来，就不用安装环境了。
你那边能不能想办法打包成 exe 程序，🙏

**Comment by trevim99** [comment]
> ahk源码得需要用户事先安装`AutoHotKey`环境，你那边打包成 exe ，其他人用起来，就不用安装环境了。 你那边能不能想办法打包成 exe 程序，🙏

好的,我晚上上傳,我剛出門了😁

**Comment by trevim99** [comment]
boomker 大佬

打包成 exe的的檔 在這。 🙏🙏🙏


[待修改-exe版-pair_symbols.lua.txt](https://github.com/user-attachments/files/17292828/-exe.-pair_symbols.lua.txt)

[move_cursor.zip](https://github.com/user-attachments/files/17292930/move_cursor.zip)



<img width="944" alt="1-exePixPin_2024-10-08_19-56-50" src="https://github.com/user-attachments/assets/9c7a006a-47c1-4fad-88ec-9222a92f0828">

**Comment by boomker** [comment]
@trevim99 
你试试把 `cmd /c start "" /B` 去掉，看看能否在不弹 cmd 窗口时，光标居中
或者：
![6a0aa07c604e07cc5f4c2f3fafa264e6](https://github.com/user-attachments/assets/b8e23d7f-ea4d-4d44-9bc2-f6a48a21c063)

11 行，改成这样试试：        move_cursor = env.user_data_dir .. [[\lua\tools\move_cursor.exe]]

**Comment by trevim99** [comment]
boomker  大佬
多謝回覆。
1.把 cmd/c startt""/B去掉，就沒移動光標的效果了。😥

2.第二種方式， cmd 窗口會閃一下，但是沒移動光標的效果。🤣
( 我二種方式改完，都有重新部署)
🙏

<img width="828" alt="test1" src="https://github.com/user-attachments/assets/ff40f4b1-d673-40ff-9dce-2fa8307e33f9">




<img width="1045" alt="test2" src="https://github.com/user-attachments/assets/54a69a33-99bd-406a-97b4-ef1e2f579af8">

**Comment by trevim99** [comment]
boomker  大佬，其實  cmd  窗口閃一下，這幾天我用過後，就閃一下，也無礙。🤣🤣
🙏

**Comment by boomker** [comment]
> boomker 大佬，其實 cmd 窗口閃一下，這幾天我用過後，就閃一下，也無礙。🤣🤣 🙏

---

不知情的用户，突然看到闪一下，会有不安全的感觉，我解释起来也挺麻烦的
cmd 黑窗闪一下，这种还是不够优雅，默认注释掉了。

**Comment by trevim99** [comment]
> > boomker 大佬，其實 cmd 窗口閃一下，這幾天我用過後，就閃一下，也無礙。🤣🤣 🙏
> 
> 不知情的用户，突然看到闪一下，会有不安全的感觉，我解释起来也挺麻烦的 cmd 黑窗闪一下，这种还是不够优雅，默认注释掉了。

我懂，我當時的想法和您一樣 😁
