### ISSUE TITLE
【提议】git ignore 用户造词文件

### ISSUE THREAD

**Issue by zhengpd** [boomker/rime-fast-xhup#73]
以下文件相当于起到了部分用户词库的作用，每个用户都产生不一样的内容，建议可以 git ignore 掉。

- en_dicts/en_custom.dict.yaml
- lua/pin_word_record.lua

原因是 fork rime-fast-xhup 使用过程中由于造词或者置顶会频繁的产生 git diff，这些 git diff 如果 commit 到本地仓库中，下次 pull rime-fast-xhup 就会产生不必要的 git conflict。

**Comment by boomker** [comment]
好的，晚上更新一版，添加上
