### ISSUE TITLE
【疑问】lua/tools/move_cursor 的作用逻辑是什么

### ISSUE THREAD

**Issue by zhengpd** [boomker/rime-fast-xhup#74]
请问 move_cursor 二进制文件有什么用？有源代码可以看吗？

**Comment by boomker** [comment]
这个是用来成对符号输出时，光标居中的。
源码我找找，找到的话，我传到 GitHub 上

**Comment by boomker** [comment]
源码找不到了，其实很简单，用的是 Go 的一个库来实现光标左移的，参考：

https://github.com/go-vgo/robotgo
