### ISSUE TITLE
引号重复输入“”“”

### ISSUE THREAD

**Issue by kailiu999** [boomker/rime-fast-xhup#76]
你好，请问，我这边输入引号的操作：
按下[shift]键 + 按下[‘’]键：输出一对引号：“”
[shift]键不松+松开[‘’]键：又输出一对引号：“”
这是为什么？

**Comment by boomker** [comment]
这个是一个 功能特性，用于成对符号输出，但是在 Windows 系统上，会感觉多输出了一个。
还是在 Windows 系统上关掉这个功能好了，感觉在 Windows 上体验不太好。
