### ISSUE TITLE
英文大写和自定义词库问题

### ISSUE THREAD

**Issue by liuy31** [boomker/rime-fast-xhup#78]
刚下载下来用，遇到了几个问题，想请教下下怎么解决，谢谢
1、 一些中间大写的单词没办法完全按照原型敲，并且自动大写没作用，例如自定义了单词 vSwitch，如果全敲小写 vswitch， 那么候选词就有且仅有 vSwitch， 如果敲全大写 VSWITCH也 是一样，候选词不会转换成全部大写；如果按照原样 vSwitch敲， 那么候选词完全不会有
![recording](https://github.com/user-attachments/assets/fb9a5002-3c3a-4d12-9556-ee1eeb4f2675)
2、、开头大写字母输入会卡顿， CPU 利用率会涨不少。正常输入 CPU在1%左右，一旦大写字母开头，就涨到3~5%，可以感觉到明显卡顿
![2](https://github.com/user-attachments/assets/a6e6e799-4c7c-498e-bb84-5344d0a08c09)

3、带有-和/的英文单词没办法加入自定义词库。改过按键，-和/已经不是以词定字的按键，在输入如 SR-IOV、 I/O 的时候，按]没办法加入自定义词库
![3](https://github.com/user-attachments/assets/30d174d8-b10e-463f-b673-16e49199a47c)

**Comment by boomker** [comment]
1. `]` 符号加入到英文的自定义词库中后， 需要重新部署才能生效的，我这边测试是正常的。 
<img width="141" alt="image" src="https://github.com/user-attachments/assets/ce3e3bc3-3344-448a-b894-71e936544db4">

2.  CPU 占用率上涨，这个是因为 Lua 脚本会对候选中的英文做转换的，不过这个占用率是会释放的，不会居高不减的。
3.  这个之前没有考虑带符号的英文单词，我改了一版上传到仓库了，你重新拉取下更新再试试。

**Comment by liuy31** [comment]
重新拉取更新后第3个问题解决了，谢谢大佬
第1个问题英文单词已经写到自定义库并且重新部署了，主要是输入vswitch 或者VSWITCH 能正常显示候选词，但是输入vSwitch的时候就完全没有显示，中间单独敲一个大写 S 就会匹配不了真正的候选
![image](https://github.com/user-attachments/assets/c210ea24-736b-433c-8b65-214a119fea80)
![image](https://github.com/user-attachments/assets/52bf07cc-f9d5-4e49-b1e2-807f0ed02395)

**Comment by boomker** [comment]
1. 输入大写未能匹配到候选的原因主要是：写到`en_custom.dict.yaml` 里的编码是全小写的，即小写编码得到原先的大写。
<img width="213" alt="image" src="https://github.com/user-attachments/assets/3825d5db-6846-4acd-a385-88c5ac66ff31">

2. `/` 符号看不到候选，这个之前没考虑到输入编码带有符号的，已经改了代码支持了，稍后推送到仓库。

**Comment by liuy31** [comment]
谢谢大佬，问题基本解决了。
另外我试了下， en_custom. lua 里面好像不用把自定义词的编码小写化，直接原样写入词库即可， melt_eng 里面已有规则会自动转换，全输入小写也能匹配有大写的词，如下：
![image](https://github.com/user-attachments/assets/8b361a9e-34b8-4ac9-8115-7bc5481cb84f)

![11](https://github.com/user-attachments/assets/26a11801-7b86-4626-baa0-ea6ad52cc6da)

再问个题外问题，我看 Rime 的 Error日志里会一直报几个 lua 的 错，这个有影响吗？出现得还挺频繁的
`E20240727 14:42:22.851249 18496 lua_gears.cc:159] LuaFilter::~LuaFilter of *easy_en*filter error(2): D:\DataFile\RimeData\lua\easy_en.lua:48: attempt to call a nil value (method 'disconnect')
E20240727 14:42:22.851325 18496 lua_gears.cc:159] LuaFilter::~LuaFilter of *word_autocommit*filter error(2): D:\DataFile\RimeData\lua\word_autocommit.lua:320: attempt to call a nil value (method 'disconnect')
E20240727 14:42:22.851421 18496 lua_gears.cc:186] LuaTranslator::~LuaTranslator of *word_autocommit*translator error(2): D:\DataFile\RimeData\lua\word_autocommit.lua:320: attempt to call a nil value (method 'disconnect')
E20240727 14:42:22.851734 18496 lua_gears.cc:244] LuaProcessor::~LuaProcessor of *commit_history*processor error(2): D:\DataFile\RimeData\lua\commit_history.lua:43: attempt to call a nil value (method 'disconnect')
E20240727 14:42:22.851803 18496 lua_gears.cc:244] LuaProcessor::~LuaProcessor of *word_autocommit*processor error(2): D:\DataFile\RimeData\lua\word_autocommit.lua:320: attempt to call a nil value (method 'disconnect')`

**Comment by boomker** [comment]
这个报错在 macOS 上没有出现，你尝试升级下 `librime` 看看。

**Comment by liuy31** [comment]
单独升级有点麻烦，先不管了，目前看没什么影响，谢谢大佬
