### ISSUE TITLE
有些字的模糊音打不出来

### ISSUE THREAD

**Issue by corwin1949** [boomker/rime-fast-xhup#79]
看了下，好像是模糊音的转换规则没有覆盖到。

可惜我不知道怎么改。

**Comment by boomker** [comment]
能否举一个例子呢

**Comment by corwin1949** [comment]
比如，xing和xin，这两个没有模糊音。

用xk(小鹤)打不出“心”字。

我看了下配置，好像是没匹配上声母（x），所以模糊音没有生效。

应该还有其他模糊音也没有匹配上。

可以换成不匹配声母的模糊音方案吗，不懂rime的设置。

**Comment by boomker** [comment]
在 `flypy_xhfast.custom.yaml` 中加上：
```yaml
      - derive/^([xbnpy])b/$1k/                  # in => ing
```

**Comment by corwin1949** [comment]
`      - derive/^([xlbnpy])b/$1k/                  # in => ing
`
我发现有个l也要加。后面发现还有什么我再补充。
