### ISSUE TITLE
一个功能请求：使用双拼，但是显示全拼码

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#81]
就像这里说的 [Rime 配置：雾凇拼音 - Dvel's Blog](https://dvel.me/posts/rime-ice/#%E4%B8%8D%E5%90%8C%E7%9A%84%E4%B8%8A%E5%B1%8F%E6%96%B9%E5%BC%8F)

如果是双拼方案，preedit_format 还可以选择是否在输入框进行转换，比如小鹤双拼输入 zz 时，是显示 zz 还是 zou。

**Comment by boomker** [comment]
配置加上了，比较奇怪的是，下面转换规则有问题：

```yaml
  - xform/([jqx])s/$1iong/
```

**Comment by boomker** [comment]
> 配置加上了，比较奇怪的是，下面转换规则有问题：
> 
> ```yaml
>   - xform/([jqx])s/$1iong/
> ```

问题解决了。
