### ISSUE TITLE
请教predict.db是什么？

### ISSUE THREAD

**Issue by Darren-Chau** [boomker/rime-fast-xhup#84]
是供联想的词库文件吗？

**Comment by Darren-Chau** [comment]
> 这个是用于移动端联想的词库

感谢解惑！

1，这是和 八股文语言模型 效果一样的吗？

2，实际上，我在iOS移动端使用您的输入方案时，打快、打长的输入状态下，延迟非常大，继续高速输入甚至会卡住，这是因为这里的 predict联想词库，和开启八股文模型的原因吗？

**Comment by boomker** [comment]
默认情况下，联想预测功能是关闭的，需要手动开启的。
输入卡顿可能是词库的问题，一些大词库可以关闭(默认关闭)
和八股文模型关系不大，你可以测试下注释掉模型相关配置，重新部署试试，看看延迟情况。

**Comment by Darren-Chau** [comment]
> 和八股文模型不是一个效果，效果就是上屏某字之后，会自动显示你可能会输入一些字。
> 
> 默认情况下，联想预测功能是关闭的，需要手动开启的。
> 
> 输入卡顿可能是词库的问题，一些大词库可以关闭(默认关闭)
> 
> 和八股文模型关系不大，你可以测试下注释掉模型相关配置，重新部署试试，看看延迟情况。
> 
> 

在iOS我用的是 仓输入法
延迟好像无关词库的问题，猜测与lua脚本有关。
还有某字上屏后联想，我在方案选单里打开没有效果，在custom里设为reset: 1也是没有效果，比如输入：“你”，它上屏后并没有联想“好”“呢”之类，有点奇怪，不知是否理解错了

**Comment by boomker** [comment]
我这边没有出现卡顿的情况，你可以录屏我看一下
联想功能，我详细测了一下，不是每次会联想，可能调一下配置试试看呢，一般我没开这个功能。

**Comment by Darren-Chau** [comment]
> 我这边没有出现卡顿的情况，你可以录屏我看一下
> 
> 联想功能，我详细测了一下，不是每次会联想，可能调一下配置试试看呢，一般我没开这个功能。


如下面视频，“在哪里见”输入四字之后，就明显感到有延迟，按键按下效果开始部分丢失，越长延迟越大。也试过其他超大词库方案，是没有这个问题的，再长也没有延迟哦。
联想功能的话是没有生效的，不知道调哪里╮(╯▽╰)╭

https://github.com/user-attachments/assets/a64e74c4-496a-4c3c-9a06-195353200bf1

**Comment by boomker** [comment]
说实话看视频，我没看出延迟大到无法接受的地步。
你那边使用的是我的整个项目方案吗？是不是有其他`Lua`？
那个联想预测，在选单里需要开启后，才能有用，但是不会是每次都能联想，不知道啥原因。

**Comment by Darren-Chau** [comment]
> 说实话看视频，我没看出延迟大到无法接受的地步。
> 
> 你那边使用的是我的整个项目方案吗？是不是有其他`Lua`？
> 
> 那个联想预测，在选单里需要开启后，才能有用，但是不会是每次都能联想，不知道啥原因。

是导入的完整的项目，没有加lua之类，，是的，看视频感觉不大，但输入时一下就能感觉出来不流畅，手感很明显的延迟阻碍感。
联想没怎么去测试，随手测的单字并没有生效。
这个困扰已久，奈何代码小白，不懂如何去排查。

**Comment by boomker** [comment]
没有加`Lua`，那就和`Lua` 脚本没有关系，
把这里的配置注释掉(加上 # 号)，重新部署试试
![image](https://github.com/user-attachments/assets/713b410d-8f26-4093-a087-db0ec7296269)

**Comment by Darren-Chau** [comment]
> 没有加`Lua`，那就和`Lua` 脚本没有关系，
> 
> 把这里的配置注释掉(加上 # 号)，重新部署试试
> 
> ![image](https://github.com/user-attachments/assets/713b410d-8f26-4093-a087-db0ec7296269)
> 
> 

感谢，确实是这里的问题！现在正常了！谢谢大佬！这是一个完美的输入方案！Y(^_^)Y

**Comment by Darren-Chau** [comment]
出现新的问题了，
手机英文输入时卡卡的
貌似是
先insert再yield多了一个写表的过程 占内存，处理时间也长了
直接yield是不是也可行呢？

**Comment by boomker** [comment]
> 先insert再yield多了一个写表的过程 占内存，处理时间也长了

---

具体哪一段代码，
如果是输入大写开头的英文出现卡顿，拉取最新的项目配置重新部署后，再试试，昨晚已经修复了这个问题。

**Comment by Darren-Chau** [comment]
> ---
> 
> 
> 
> 具体哪一段代码，
> 
> 如果是输入大写开头的英文出现卡顿，拉取最新的项目配置重新部署后，再试试，昨晚已经修复了这个问题。

我是说/oe英文输入，但是刚刚导入了最新的项目，好像已经没有问题了哈^_^
