### ISSUE TITLE
macOS无法修改成减号和等号翻页

### ISSUE THREAD

**Issue by NecerLixin** [boomker/rime-fast-xhup#85]
修改了flypy_xhfast.custom.yaml中这里的设置，重新部署了，但是还是无法使用减号和等号翻页，仍旧是逗号句号翻页
<img width="988" alt="image" src="https://github.com/user-attachments/assets/642dec77-806f-4d1b-bb09-dace3dc17fc4">

**Comment by boomker** [comment]
更新了一版，拉最新项目方案配置，再改改试试看下

**Comment by NecerLixin** [comment]
> 更新了一版，拉最新项目方案配置，再改改试试看下

没问题了，感谢🙏
