### ISSUE TITLE
有关于超级简拼

### ISSUE THREAD

**Issue by skowosy** [boomker/rime-fast-xhup#86]
作者你好，我想在其他方案上实现这个功能。
您能教我如何实现吗

**Comment by boomker** [comment]
配置文件里有对应的注释哦，
https://github.com/boomker/rime-fast-xhup/blob/5c94f3a5ad7e8e0f7168b3a3ec2d16db33a93ca0/flypy_xhfast.schema.yaml#L337-L339

这个是最简单的，但可能部分人开启后有卡顿的情况，你可以试试看。
另外一种方式，就是自己整一个自定义词库，把简拼编码和对应的汉字词条写进去就好，参见 idiom_phrase.txt

**Comment by skowosy** [comment]
就是那个快捷键『control+0』怎么实现的，我加了    - lua_processor@*idiom_abbr_expand但不起作用

**Comment by skowosy** [comment]
您说的那个地方我也开了，也不起效

**Comment by boomker** [comment]
这行有配置吗？
https://github.com/boomker/rime-fast-xhup/blob/5c94f3a5ad7e8e0f7168b3a3ec2d16db33a93ca0/flypy_xhfast.custom.yaml#L60

这个 Lua 也要在你的方案里
https://github.com/boomker/rime-fast-xhup/blob/5c94f3a5ad7e8e0f7168b3a3ec2d16db33a93ca0/lua/idiom_abbr_expand.lua

**Comment by skowosy** [comment]
我用的雾凇没有这个文件啊

**Comment by boomker** [comment]
> 我用的雾凇没有这个文件啊

单独把这个 Lua 脚本放进去呗

**Comment by skowosy** [comment]
我放进去了
