### ISSUE TITLE
2个前缀模式无法使用

### ISSUE THREAD

**Issue by transread** [boomker/rime-fast-xhup#87]
我的系统是win10，有2个前缀模式无法使用：

/so，无法切换横纵布局，切换文字方向无法变回原来的方向
/vs，计算器解析失败，无法使用计算功能

**Comment by transread** [comment]
请问如何添加自造字？

我的意思是通过快捷键将自造词自动添加到用户词库中

**Comment by boomker** [comment]
> /so，无法切换横纵布局，切换文字方向无法变回原来的方向
> /vs，计算器解析失败，无法使用计算功能
> 通过快捷键将自造词自动添加到用户词库中

---

切回原来的文字方向，需要在一个新的应用里操作才会生效，它没法在原有的应用里切回，具体原因我也不知道🤷‍♂️
解析失败，发一下你的计算表达式，我试试看，一些简单的运算是没有问题的。
没有什么快捷键来添加自造词，自造词是通过「`」这个符号筛字上屏就会自动进入到你的用户词库里的

**Comment by transread** [comment]
感谢回复，刚才重新安装部署了一下，计算器功能没问题了。

但是自造词……有点问题。

- 我键入grove，不显示“精准造词”字样;
- 键入 grove + 双拼 完成选词后，会出现“` + 自造词“，例如：

![Uploading 微信截图_20240916114033.png…]()

**Comment by transread** [comment]
感谢回复，刚才重新安装部署了一下，计算器功能没问题了。

但是自造词……有点问题。

我键入grove，不显示“精准造词”字样;
键入 grove + 双拼 完成选词后，会出现“` + 自造词“，例如：

![微信截图_20240916114033](https://github.com/user-attachments/assets/5f3e2c19-d2e2-46a0-b791-4ee42512d39d)

请问该如何解决？

**Comment by boomker** [comment]
> 不显示“精准造词”字样

---

这个之前在 `patterns` 里没写正确的正则，但其实很少用前缀的方式来造词， 刚更新了一版，现在可以前缀造词了
![image](https://github.com/user-attachments/assets/317266ff-2275-4eb2-bfa7-eafb6d9a8aca)

**Comment by transread** [comment]
更新后，自造词又失效了……

**Comment by transread** [comment]
老毛病，按grove + 双拼，无法造词。

![image](https://github.com/user-attachments/assets/562716b2-715f-4f77-843e-0c209ea48d7d)

感觉造词功能是不是可以换一个快捷键……

另外更新后发现无法显示“方案选单”。

我的设置是 f3 / alt + grove，系统为win

**Comment by boomker** [comment]
![图片](https://github.com/user-attachments/assets/1ed007d0-89c4-45d3-9732-9f86df673134)
手动造词的姿势是这样的：
在双拼音码后面按下 ``grave(`)`` 追加形码，不能只是按下 `` ` ``打头

---

> 另外更新后发现无法显示“方案选单”


可以在这里添加你的快捷键：
https://github.com/boomker/rime-fast-xhup/blob/b8680c6a6bd719b9bb9cdbbefa385f93c282f3e9/default.custom.yaml#L19
