### ISSUE TITLE
能否变更一下 / 筛选单字的功能

### ISSUE THREAD

**Issue by transread** [boomker/rime-fast-xhup#89]
> 支持斜杠 / 过滤单字和词组(匹配单字的音形四码), 比如输入 uu/i 自动上屏「输」

能不能将这个功能改造成输入辅助码后，如果显示词组而非单字，按 / 后变成单字

**Comment by boomker** [comment]
可以加上一个开关，是否默认自动上屏。不默认自动上屏，就把单字优先级提升显示在候选菜单里。

**Comment by boomker** [comment]
刚更了一版，默认是按下 `|` 进入单字模式，可配置

**Comment by transread** [comment]
到工位就更新了一下，体验棒👍，感觉今天的牛马生活一下子快乐了许多 😂

顺便歪个楼，请问我平时键入的常用词都存储在了哪里呢？能不能导出？

**Comment by transread** [comment]
发现一个bug。| 对词组中的尾字无效……

![微信截图_20240927102420](https://github.com/user-attachments/assets/fb5316d6-ed57-4680-9620-43f9d2e77523)

![1](https://github.com/user-attachments/assets/fee881b1-90ab-4e27-b7e4-68ee3fe3cc47)

**Comment by boomker** [comment]
> 顺便歪个楼，请问我平时键入的常用词都存储在了哪里呢？能不能导出？

经常键入的字词会被记录到用户词库里，用户词库需要手动同步后默认写入到 `sync`  文件夹里，这样就算是导出了，
 Windows 系统的话，Rime 好像自带导出导入的图形化工具。

> 对词组中的尾字无效

`|` 目前只对4码二字词组转为单字模式，你这种是有已确认的音节(厂部)开头了，后续的四码就没效了。
如果你要过滤词组，可以按`/`，会对尾字过滤；
如果是在有已确认音节的情况下，四码转单字，暂时还没支持，我看情况试试支持

**Comment by Well-key** [comment]
我现在flypy_xhfast.custom.yaml是以上设置：
![image](https://github.com/user-attachments/assets/c1b54804-37cb-4209-9a64-fd910c41d974)

![image](https://github.com/user-attachments/assets/30521597-099c-40c3-bf0d-161bec936a54)

![image](https://github.com/user-attachments/assets/6440e2b1-e1ec-4c92-b23c-96fd1ce77430)

有以下问题：
1. “|”键不能单字优先出现如下问题
2. “`”与“/”好像都能直接引导辅码；
3. 原来设定的直接辅码不起作用了，而且这个功能与使用间接引导辅码有啥区别呢？

![1](https://github.com/user-attachments/assets/fc415d78-857c-48a2-8149-2d4910bd1c3e)

**Comment by boomker** [comment]
> “|”键不能单字优先出现如下问题
> “`”与“/”好像都能直接引导辅码；
> 原来设定的直接辅码不起作用了，而且这个功能与使用间接引导辅码有啥区别呢？

1.  在主配置里加上：
```YAML
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA89_-`/|\
```

2.  区别：「\`」是造词，生词会进入到用户词库；
                `/` 既可以间接辅码过滤尾字，也可以在四码二字词时，过滤词组，词组优先；
                `|` 是四码输入完后转单字的音形码，单字优先。

更新：
> 在有已确认音节的情况下，四码转单字

这个支持了，放开了正则匹配限制。

**Comment by transread** [comment]
👍
