### ISSUE TITLE
能不能符号直接上屏啊

### ISSUE THREAD

**Issue by calmwaves111** [boomker/rime-fast-xhup#9]
![Snipaste_2023-10-05_21-13-43](https://github.com/boomker/rime-fast-xhup/assets/56907077/b8164606-a239-4b45-8564-ce28b4d5699d)
比如这个，我就算改成了只有一个字符，也是
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/6e37dde5-14c2-4bec-b719-095f5de6cc2f)

**Comment by calmwaves111** [comment]
还有自造词如果和词库里有编码的话，就不能记录啊
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/f6d3a372-e6fa-409e-8746-5958582e8e14)
词库里有 zizc 这个编码
所以即使我造了`字造`这个词，还是记不住
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/51cd4795-52e0-403a-b14b-9018debed8db)

**Comment by calmwaves111** [comment]
我把逗号选首字和句号翻页的功能都注释了
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/abd5b03b-c813-4b91-8d75-3779b19df2a0)
但是现在逗号和句号也不能顶字上屏
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/bc7d7e31-f70c-4cf3-a5a9-9c275044f425)
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/0734821e-9c12-4487-82aa-7d0ad0faea55)

**Comment by edison0808** [comment]
会不会是你为你造了词  但可能实际并没有造到

**Comment by calmwaves111** [comment]
> 会不会是你为你造了词 但可能实际并没有造到

确实没有造到，就是词库有编码的，就不能再在这个编码下造词了，如果词库里没有这个编码，就能记住

**Comment by boomker** [comment]
@calmwaves111 
1. 「$」直接上屏：注释掉 ` "$": [￥, "$", "€", "£", "¥", "¢", "¤", ₩]`这行配置，如果还是不生效，删掉 `build`文件夹下`flypy_xhfast.schema.yaml` 配置文件。
2. 「字造」自造词的正确用法是： 依次输入` zi[bzc` ，光标最好停留在末尾，然后上屏
3. 「，。」直接上屏：之前有 bug， 刚更新了一版，你再试试

**Comment by calmwaves111** [comment]
太感谢大佬的快速修复了
1. 我直接注释掉之后还是不能符号直接上屏，然后我照猫画虎又加了这么两句，果然让 default.yaml  里的半角符号生效了
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/625614fd-c044-44e6-a9df-7e09664d1dfa)
2. 关于这个自造词目前只能用辅助码来造词吗，直接双拼不行？我觉得您应该是参考了 https://github.com/functoreality/rime-flypy-zrmfast 这个库的，flypy-zrmfast就能用双拼造词
3. 「，。」直接上屏的问题已经修复了

---
下面您可以不用看，我只是想表达我的感谢
我是从搜狗输入法转过来的，搜狗里用的是小鹤双拼加自定义短语挂接小鹤形码的辅助码，我没有专门练习形码都没记住码表，大部分都是靠双拼打字，偶尔用形码辅助选一下字，搜狗其实做的真的不错，但是我考虑到隐私和广告问题，还是趁着国庆假期狠狠心转了 rime
虽然早就听说了雾凇拼音的大名，但是没有小鹤双拼挂形， 于是我在  GitHub 上搜索找了关于小鹤双拼的方案，我找到了两个库，一个是您的库，一个是https://github.com/functoreality/rime-flypy-zrmfast，其实刚开始打算用您的库，但当时小白不懂，下载了半天部署不成功，所以刚开始用的flypy-zrmfast，折腾了几天也对 rime 配置熟悉了点，flypy-zrmfast对于中英混输的支持不太好
所以我重新搜索了这个库的 issue， 发现部署不成功是因为词典太大了，果然我注释掉那几个大词库之后就部署成功了
您的方案对我真的十分有用，而且您还在坚持更新，也积极处理 issue， 真的十分感谢您

**Comment by calmwaves111** [comment]
最后有一个小需求，如果您感兴趣可以考虑一下，不感兴趣您可以直接忽略

目前有了一个数字后面的句号和冒号自动转半角，能否实现这样一个功能，连续两个全角就自动转为一个半角，大致实现思路是这样的，以逗号为例：
记录提交历史，在按下全角逗号时，如果上一个提交为全角逗号，那么发送一个退格键和一个半角逗号,

这个我在 rime 官方 issue 里提过，但是官方不考虑，https://github.com/rime/home/issues/1386

我找到了数字后句号和冒号自动转半角的软件内部的代码，这个功能被写死在librime的代码中， 
https://github.com/rime/librime/blob/fe5a65deb1348cd1b45702ded0041029add6dadd/src/rime/gear/punctuator.cc#LL75C1-L75C1

我不确定能否用 lua 实现，因为我对 lua 一窍不通，重申一下，您感兴趣可以考虑一下，不感兴趣您可以直接忽略，您现在的库已经帮助我很多了，再次感谢您的贡献

**Comment by calmwaves111** [comment]
又有新的问题了^和_不能多选
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/a26a0531-2510-43f9-ae0e-eb7b58a7692b)

**Comment by boomker** [comment]
1. `$`直接上屏：配置文件注释掉，或只保留一个符号；  `^_`多选：在配置文件里加上多个符号。
2. 关于造词：通过逐个选字词的方式来造词，在某一些时候是不生效的，这个感觉和 Rime 的机制有关，可以写一个分词器脚本来记录并实现上屏词条下次输入编码居于第一候选项。通过辅助码来造词是百分百可以确定下次输入相同编码，候选词居于第一位。
3. 连续输入两个全角符号转为半角符号：这个我可以尝试一下，可能没想象中的那么容易好实现。

----
刚更新了一波，可以拉下更新，再尝试一下。
感谢你的积极反馈，正是有像你这样的热心朋友，开源项目质量才能越来越好，我自己没法覆盖所有的使用场景和个人偏好，所以是得感谢🙏🏻你才对，也希望更多朋友参与到开源项目的活动中来，让大家都能从开源项目中获得体验更好的成果。

**Comment by calmwaves111** [comment]
1. 关于符号还是有点问题，我的期望目标是这样，所以我把default.yaml文件做了点改动
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/cfd0efef-5fc2-41e2-8919-6f7300cace80)
然后我修改了flypy_xhfast.schema.yaml
![image](https://github.com/boomker/rime-fast-xhup/assets/56907077/50e33352-1279-4e6f-ae8f-c2d2df6182ef)
我有三处多选，`\`，`^`和`_`，但是只有`\`能多选，其他两个只能直接上屏第一个符号，而且不止是`^`和`_`，我发现`@`,`&`还有好几个都是这样，就算配置了多选也只会上屏第一个，不会出现多选列表
2. 造词的问题解决了，现在很好
3. 感谢您对连续全角转半角的需求有兴趣

**Comment by calmwaves111** [comment]
嗯我可以确定我的配置是生效的，因为如果我改成`"_": [a,'——']`，那按下`_`键就会直接上屏`a`，所以会上屏多选列表里的第一个，但是不会出现多选列表

**Comment by boomker** [comment]
按照你的配置，我这边测了一下，是可以出现多选列表的。
<img width="136" alt="image" src="https://github.com/boomker/rime-fast-xhup/assets/19751472/7a52a454-57a2-43f9-9e48-40b5b84c1b79">

---
你那边需要检查:
1.  Git 拉取项目最新的 [commit](https://github.com/boomker/rime-fast-xhup/commit/92695d1692dde5a5d68fd39f6680a0378ce450b7) 提交到本地
2. 检查 build 配置里`default.yaml`  文件里的内容和你之前配置的一样
3. 点击图标，重新部署

**Comment by calmwaves111** [comment]
我卸载了之后重启，再重装，重新部署本方案，突然就能多选了
之前出现的bug不知道原因，但没事现在能用了
打扰您了
