### ISSUE TITLE
有关于Fcitx5辅助功能权限问题

### ISSUE THREAD

**Issue by Anber55** [boomker/rime-fast-xhup#90]
由于Fcitx5没有系统签名，导致每次更新之后都需要重新开启辅助功能权限才能使用光标居中，但是最近一直失败，操作步骤是：
在辅助功能内删除Fcitx5，然后在Finder中打开/Library/Input Methods/Fcitx5.app，将Fcitx5重新添加到辅助功能权限
操作完之后还是不能光标居中

**Comment by boomker** [comment]
按照这样操作试试：
![image](https://github.com/user-attachments/assets/bfaf5f1b-a3da-49f9-8404-1fd42e36f8c4)
选中小企鹅，点击下方的减号「➖」删除，然后输入成对符号，会弹出提示框让你重新添加，添加完后，下次就能光标居中了。​

**Comment by Anber55** [comment]
我知道为什么了，我用的Fcitx5的卷轴模式，一直不行，换到普通模式就可以了，好奇怪

**Comment by boomker** [comment]
> 我知道为什么了，我用的Fcitx5的卷轴模式，一直不行，换到普通模式就可以了，好奇怪

仔细测了一下，这个卷轴模式没法检测到，现有的` librime-Lua` 接口识别不到卷轴模式下的按键

**Comment by Hodwe** [comment]
明白，那就不用这个卷轴模式了

**Comment by boomker** [comment]
这个问题可以到` Fcitx5-macos` 项目提  issue， 寻求帮助
