### ISSUE TITLE
中英混打有機會實現(半形的)數字+英文+ 符號也能混打嗎

### ISSUE THREAD

**Issue by trevim99** [boomker/rime-fast-xhup#91]
boomker大佬

請問飛鶴快拼在中文輸入模式下的中英混打有機會實現(半形的)數字+英文+ 符號也能 中英符號+數字混打嗎？
 (編修markdown時應該會很好用💪🏻)=(數字，半形符號不要中文上屏) 謝謝🙏

例如：
 rime-123   
 rime01  
 a+b=c 
 a+1=5 
 [[xyz-moc]]  
 ![123.jpg]等等

🙏

**Comment by boomker** [comment]
如果设定了数字是选字上屏的，那么这个需求是没法完全实现的，只能部分实现，比如这样：
![image](https://github.com/user-attachments/assets/0e46af5a-b051-41b5-a266-66bc0ab0aa3e)

![image](https://github.com/user-attachments/assets/7035033e-4401-42f6-8585-3dfbbcdf5da7)
　　
 或许可以这样实现：
设定一种前缀模式，这个模式只翻译输入，不翻译到汉字，然后进入到这个模式就行了。
