### ISSUE TITLE
🙋‍♂️计算器支持 百分比/千分比/万分比运算🙏

### ISSUE THREAD

**Issue by trevim99** [boomker/rime-fast-xhup#92]
請問 /vs 前綴：計算器做乘法時， 有可能實現直接加入 %、‰、‱ (百分之一符號，千分之一符號，萬分之一符號)
計算及輸出嗎？ 🙏

(不好意思，我用txt貼上github，格式會異常，所以用截圖貼上，🙏)
  
![image](https://github.com/user-attachments/assets/c72b8124-7565-422a-bd06-6ba554afaf13)

**Comment by boomker** [comment]
想法很棒，键盘上已有的`%`也是也是一种运算，所以不能作为百分比，可以用下面的方式替代，
*  h： 代表100
*  q： 代表1000
*  w： 代表10000
*  b： 代表1000000

![image](https://github.com/user-attachments/assets/abd335dc-80c0-4c13-bacd-76f1b05ccbdb)　

![image](https://github.com/user-attachments/assets/ce6bd7cc-66a8-4966-85f8-6833959948aa)

![image](https://github.com/user-attachments/assets/390a7a74-40e9-4a86-bdec-ea9f91ecf4a1)

**Comment by trevim99** [comment]
> 想法很棒，键盘上已有的`%`也是也是一种运算，所以不能作为百分比，可以用下面的方式替代，
> 
> * b： 代表100
> * q： 代表1000
> * w： 代表10000
> * m： 代表1000000
> 
boomker 大佬：

一、請問計算器加 ％ ､‰､ ‱運算時
有機會實現上屏時能用％ ､‰､ ‱直接上屏嗎？ 謝謝
(％ ､‰､ ‱這三個符號是最常用的，直接上屏可以簡化輸入)

  (候選框)           	              ( 上屏)
333*3/b=9.99       上屏爲 333*3％=9.99  

333*6/q=1.998     上屏爲 333*6‰=1.998

333*6/w=0.1998  上屏爲 333*6 ‱=0.1998 

二、另外計算器能更改候選框的次序?
左圖的 2.運算式及結果 與 1.結果 調換順序
希望【運算式及結果】優先置頂。謝謝🙏
🙏



![image](https://github.com/user-attachments/assets/c628e229-c4f3-41d6-a77c-1623826855fd)
