### ISSUE TITLE
🙋‍♂️FR: /hs 的上屏歷史存档需求支持？🙏

### ISSUE THREAD

**Issue by trevim99** [boomker/rime-fast-xhup#93]
🙋‍♂️請問 /hs 的上屏歷史是存在那個檔案？ 謝謝

如果沒有存檔，請問能增加功能選項存在硬碟嗎？😅
(方便日後復用)

◎Rime 的 ## 格式：文本-输入码-权重，其间用 Tab 符分隔。

😍如果能存檔，請問能存成 user_history.txt
格式：文本-输入码-上屏日期(例如：20241005)(≒最高權重)

謝謝

🙏

**Comment by boomker** [comment]
上屏历史目前没有存档功能，存档这个需求如果要支持的话，也只能手动定期触发，自动触发的话，输入法的负担就大了
话说，你为啥有存档需求呢，之前我没考虑过

**Comment by trevim99** [comment]
> 上屏历史目前没有存档功能，存档这个需求如果要支持的话，也只能手动定期触发，自动触发的话，输入法的负担就大了 话说，你为啥有存档需求呢，之前我没考虑过

您好

目前的思路😅：
一、一般人工作或生活上常在打的 字(單個字)，詞組，句子有習慣性。
history(上屏歷史)可以整理成個人專屬的簡拼詞庫。

二、有history資料庫的話，也許有機會能發展成類似vscode 或vim 的 auto-complete 的功能。(選字範圍限定在history ，應該會更精準🤣)

三、⭐方便復用。


🙏🙏🙏

**Comment by trevim99** [comment]
> user_history.txt

另一個思路是，如果把user_history.txt 視爲 temp(暫存池)，暫存池裏面有很多魚(語)，有一條魚叫【復用】，如果在一定時間內(例如3天)，user 打【復用】3次，也許可把【復用】視爲 user 的習慣用語，即可把【復用】這條魚🐟移入 flypy_xhfast.dict.yaml的(永久池)自定義詞庫。
(以上這些如果用腳本可自動完成太棒了🤣)

**Comment by boomker** [comment]
Rime 有自带的用户词库功能，已上屏的字词都会记录的，用户词库里也有记录上屏次数，文件格式也是 txt， 只不过要手动同步才会有，你可以把用户词库文件单独处理。默认用户词库放在` sync ` 目录里，文件名：`flypy_xhfast.userdb`

**Comment by trevim99** [comment]
😍我還有一個天馬行空的優化想法😅：
Windows的Rime小狼毫是 用 【Space】上屏，
如果打字時，已經在候選框選出user想要的詞組，例如 「宋太祖趙匡胤」(6個中文字)，
如果能實現其他(組合)鍵(ex 【Ctrl】+【y】 )，可以 上屏+加字加詞組到custom_phrase.txt(或自定義詞庫)+加上頭音簡碼(stzvky)(=sstdzuvcklyb)+詞頻(權重)
💪🏻應該會很棒💪🏻
(這有點類似 vscode snippet 或 MS-Word autotext自動圖文集的概念)
(6個中文字≒N個中文字)
🙏🙏🙏

![image](https://github.com/user-attachments/assets/3959dd90-d3b4-4163-b710-82c0ba1f86b6)

**Comment by boomker** [comment]
简拼大多数是直接支持的，少数需要按` Ctrl+0 ` 展开，而且双拼输入过并上屏了，下次也能直接简拼
所以，将简拼编码和对应词条写入到词库的必要性没那么大，可以考虑把展开的简拼对应词条快捷加入到置顶词库。

**Comment by trevim99** [comment]
> 简拼大多数是直接支持的，少数需要按`Ctrl+0` 展开，而且双拼输入过并上屏了，下次也能直接简拼 所以，将简拼编码和对应词条写入到词库的必要性没那么大，可以考虑把展开的简拼对应词条快捷加入到置顶词库。

多謝回覆。 🙏


1.双拼输入过并上屏了，下次也能直接简拼》請問這要怎麼做出來？ 我用 蔡大虎 測試，好像不成功，可能是我操作有誤。


<img width="437" alt="c1" src="https://github.com/user-attachments/assets/1ce8c75a-5dd7-4c55-a70a-c6f794e00af4">

2.少数需要按`Ctrl+0` 展开》 請問這個功能，能給我操作的step或例子嘛？ 這個 `Ctrl+0` 展开，我也一直試不出來，謝謝。🙏



<img width="313" alt="2" src="https://github.com/user-attachments/assets/b575c0a4-8ecf-4eb4-902b-882005416e13">

**Comment by boomker** [comment]
![image](https://github.com/user-attachments/assets/c755a53d-0130-4871-8917-4dd231f4292c)
![image](https://github.com/user-attachments/assets/462ae9cf-ccfc-45d7-b08b-52b3b96dc8ca)

` Ctrl+t ` 目前还没支持简拼，我之前的意思是，我可以考虑支持实现这个功能

**Comment by trevim99** [comment]
>
> 这个不是所有词条都可以，一般得是词库里存在的，上屏之后简拼没出来的，再按`Ctrl+0` 应该是能找到的

我終於懂`ctrl+0`了😂

🙏🙏🙏
