### ISSUE TITLE
launch产生错误

### ISSUE THREAD

**Issue by Anber55** [boomker/rime-fast-xhup#94]
最近使用这个lua时又产生了一些问题，例如

输入数字确认会直接上屏
输入空格确认也会直接上屏
只有输入字母才会运行代码

另外也出现了没有直接到达vvi的情况

产生了对应的错误：
E20241005 20:51:07.001545 0x16d52b000 lua_gears.cc:229] LuaProcessor::ProcessKeyEvent of *launcher*processor error(2): /Users/ZiYan/.local/share/fcitx5/rime/lua/launcher.lua:137: attempt to index a nil value (local '_cmdString')

演示视频如下：

**Comment by Anber55** [comment]
Uploading Built-in Retina Display.mp4…

**Comment by Anber55** [comment]
https://github.com/user-attachments/assets/4ddbf64f-229a-4188-b1a6-e97c9d8df9cd

**Comment by boomker** [comment]
我这边没有浮现出来，你尝试把触发前缀改成默认配置`/fj`试试看，
如果还是有问题，把你的配置`lua/launcher_config.lua`(自行脱敏) 发我测一下

**Comment by Anber55** [comment]
抱歉，我在脱敏的时候发现，数字没有按照顺序摆放，所以出现了通过空格和数字无法选择的情况，现在好了，感谢，但是还是极少会出现输入的是正确命令的编码，但是没有出现对应的命令选项

**Comment by boomker** [comment]
> 但是还是极少会出现输入的是正确命令的编码，但是没有出现对应的命令选项

---
已经修复了，拉下最新项目配置再试试看下
