### ISSUE TITLE
🙋‍♂️請問有機會實現上屏時，自動加上前後符號或字串？

### ISSUE THREAD

**Issue by trevim99** [boomker/rime-fast-xhup#95]
🙋‍♂️如果是要簡化輸入， 請問有機會實現，候選框選好詞組後，
要上屏時，按功能鍵或後綴，上屏的結果是自動加上
 「前後標點」或【自定義(特殊)符號】或 【前後字串】？😍

上屏的結果：   【紅茶】 **奶茶** 「烏龍茶」

上屏的結果： 鄭曉 女士

🙏🙏🙏

<img width="584" alt="優化" src="https://github.com/user-attachments/assets/2fd24fbd-7340-442b-9135-0150a9764800">

<img width="312" alt="優化2" src="https://github.com/user-attachments/assets/f8e49e00-1a85-4ca4-880c-4f1136c23ff2">

**Comment by trevim99** [comment]
> 这个用 Lua 实现不难，每种成对符号可以对应一个快捷键，或者用一个文件专门存放需要前后自动添加指定字符的候选。 这个需求比较小众，就不打算放到项目里，你要有需要，我写一个 Demo，你拿过去用。

boomker 大佬 
DEMO再拜託了,謝謝您  🙏🙏🙏

**Comment by boomker** [comment]
这个功能放到项目里了，可以直接用，或者自行修改按键，参考：
https://github.com/boomker/rime-fast-xhup/blob/aec9948a816d656a6db0033e69bb2b98f2bbaa40/lua/pair_symbols.lua#L86-L102

**Comment by trevim99** [comment]
> 这个功能放到项目里了，可以直接用，或者自行修改按键，参考：
> 
> https://github.com/boomker/rime-fast-xhup/blob/aec9948a816d656a6db0033e69bb2b98f2bbaa40/lua/pair_symbols.lua#L86-L102

謝謝 大佬
這功能應該是會很實用(簡化輸入) 🙏
(好像其他輸入法還)

> 这个功能放到项目里了，可以直接用，或者自行修改按键，参考：
> 
> https://github.com/boomker/rime-fast-xhup/blob/aec9948a816d656a6db0033e69bb2b98f2bbaa40/lua/pair_symbols.lua#L86-L102

大佬👍👍👍

成功了,太赞了
成功的效果很棒
成功的效果如图片
谢谢您
🙏🙏🙏
😁😁😁

(
细节的调整: 
1. 脚本中的 cand.text and 拿掉就ok了
2. 我用 windows , 不知何故,control + shift + 【N】 键  的组合做不出来,只能用 ctrl + 【N】 键,不过不影响.
 )




![image](https://github.com/user-attachments/assets/b1e782ca-dfec-4549-9018-183319f56b9e)
