### ISSUE TITLE
🙋‍♂️請問候選框的預設排序，謝謝

### ISSUE THREAD

**Issue by trevim99** [boomker/rime-fast-xhup#96]
boomker大佬
🙋‍♂️請問我希望已經上屏過的語詞或單個中文字或⚡️emoji， 上屏過後，如果下次打出同樣的小鶴雙拼碼(xnheulpbma) 或 簡拼碼(jpm) 時，都能優先出現在候選框(預設排序優先)／( 不需要再每個詞組 Ctrl+  t 的手動置頂), 請問要改哪些設定？ 🙏

例如： 謝謝

![image](https://github.com/user-attachments/assets/e04c06ce-8550-4c8e-a3d8-4ce7a7a5959c)

**Comment by Lion176** [comment]
@boomker 

> 如果是简拼码，下次相同输入，候选项位置优先靠前，这个 Rime 有调频机制，但是似乎不总是生效的，
用Lua脚本可以实现(目前未支持)，后续考虑支持

![Image](https://github.com/user-attachments/assets/a6e018fe-6e78-484f-a4cf-0776ebb969d1)

请教一下：我输入 jpj ，候选词是：J盘，键盘，解决。多次输入"解决"后，"解决"的词频还是没有变化，这是不是相同的问题？

**Comment by boomker** [comment]
> 请教一下：我输入 jpj ，候选词是：J盘，键盘，解决。多次输入"解决"后，"解决"的词频还是没有变化，这是不是相同的问题？

---

输入`jpj` 不是简拼码，简拼码就是双拼的声母(音码第一位)；
我这边输入`jpj` 上屏多次"解决"后，它的词频会调频到最高(候选第一位)
简拼码(超级简拼)这个特性目前来说体验不是很好，尤其是词库比较大的时候，我默认关闭了
方案里有`idiom_phrase.txt`，这里面的短语也能做到类似简拼码的输入，不过不会调频的

**Comment by Lion176** [comment]
> > 请教一下：我输入 jpj ，候选词是：J盘，键盘，解决。多次输入"解决"后，"解决"的词频还是没有变化，这是不是相同的问题？
> 
> 输入`jpj` 不是简拼码，简拼码就是双拼的声母(音码第一位)； 我这边输入`jpj` 上屏多次"解决"后，它的词频会调频到最高(候选第一位) 简拼码(超级简拼)这个特性目前来说体验不是很好，尤其是词库比较大的时候，我默认关闭了 方案里有`idiom_phrase.txt`，这里面的短语也能做到类似简拼码的输入，不过不会调频的

不知道是哪个设置会影响这种不完整的简拼码的候选词的排序，如果是完整的编码，候选词是会根据上屏的频率调整词频的。

另外还有一个配置不太明白，想请教一下：
translator:
  enable_user_dict: true # 开启用户词库
  enable_encoder: true              # 是否开启自动造词〔仅table_translator有效〕
enable_user_dict: true，这个设置开启用户词库就会自动造词，那么  enable_encoder: true 这个是哪种类型的自动造词呢？

**Comment by boomker** [comment]
>  enable_encoder: true 这个是哪种类型的自动造词呢？

---

这个配置项只适合纯形码(五笔)的方案来造词的，形码方案一般不用词库，或词库很小，通常只有码表，
这个配置项就是在仅有码表的情况下根据输入码来自动成词。

**Comment by Lion176** [comment]
> > enable_encoder: true 这个是哪种类型的自动造词呢？
> 
> 这个配置项只适合纯形码(五笔)的方案来造词的，形码方案一般不用词库，或词库很小，通常只有码表， 这个配置项就是在仅有码表的情况下根据输入码来自动成词。

双拼用户，不需要开启 enable_encoder: true，对不？

**Comment by boomker** [comment]
> 双拼用户，不需要开启 enable_encoder: true，对不？

---

对的

**Comment by Lion176** [comment]
> > 双拼用户，不需要开启 enable_encoder: true，对不？
> 
> 对的

感谢大佬回复！
前面提到的不完整拼写词频自动调整的问题，不知道是不是跟方案的拼写规则有关，不太懂。
我之前使用的是雾凇拼音方案，没有遇到过类似问题。在最开始切换rime-fast-xhup方案的时候，还有一个典型的例子：
开启了简拼的情况下，雾凇拼音方案：我输入 `een `，候选词可以直接输出 `嗯嗯`，但是rime-fast-xhup方案里，不能这样。
如果大佬知道这个具体原因，还希望指导一下。

**Comment by boomker** [comment]
> 前面提到的不完整拼写词频自动调整的问题，不知道是不是跟方案的拼写规则有关

我知道你的问题了，开启简拼的情况下，`jpj` 是 "J 盘"的完整编码，输入法程序会优先将完整编码的候选字词排在最前面
这种情况下，可以用`Ctrl-t`将指定候选字词(解决)强制放到第一位，或者`Ctrl-d`将"J 盘"隐藏或降频(`Ctrl-j`)

> 开启了简拼的情况下，输入 een ，候选词可以直接输出 嗯嗯

![Image](https://github.com/user-attachments/assets/fdb8dbf1-a627-4ea2-85bb-fac7cfcbd3a6)

**Comment by Lion176** [comment]
> > 前面提到的不完整拼写词频自动调整的问题，不知道是不是跟方案的拼写规则有关
> 
> 我知道你的问题了，开启简拼的情况下，`jpj` 是 "J 盘"的完整编码，输入法程序会优先将完整编码的候选字词排在最前面 这种情况下，可以用`Ctrl-t`将指定候选字词(解决)强制放到第一位，或者`Ctrl-d`将"J 盘"隐藏或降频(`Ctrl-j`)
> 
> > 开启了简拼的情况下，输入 een ，候选词可以直接输出 嗯嗯
> 
> ![Image](https://github.com/user-attachments/assets/fdb8dbf1-a627-4ea2-85bb-fac7cfcbd3a6)

大佬确实厉害，一出手，药到病除，问题全部解决了！感谢感谢~
