### ISSUE TITLE
tab 键使用辅助码后的光标位置问题

### ISSUE THREAD

**Issue by transread** [boomker/rime-fast-xhup#98]
使用tab键使用辅助码模式后，光标会自动转到词尾，如 **fuvuma**

![image](https://github.com/user-attachments/assets/76ce7847-4d79-4d27-959f-0d30c3915aaa)

这样用起来十分不方便，能不能让光标移动到下一个字的字尾——也就是说，以“fuvuma”为例，fu使用辅助码后，光标跳到vu的末尾，而非ma的末尾。

**Comment by boomker** [comment]
写了一个简单的补丁，可以缓解这个问题，给 `辅(fu)` 加上辅码 (i) 后，继续按下`Tab`键会定位到`vu`后面。

**Comment by transread** [comment]
刚刚更新了，这个功能没问题。但是新问题出现了。tab 在不使用输入法时无法让光标向右缩进了

**Comment by boomker** [comment]
> tab 在不使用输入法时无法让光标向右缩进了

这个没太懂，能截图或录屏看看吗，是在什么软件环境下使用的？

**Comment by transread** [comment]
![Tab](https://github.com/user-attachments/assets/3cd85acb-ba05-41ad-9dcc-66938cb5ecd8)

如图所示：

第一行，在手心输入法下，不使用输入法打字，按tab键，光标向后移动——缩进。

第二行，使用本方案，在不使用输入法打字的情况下，按tab键，光标不移动。

我用的是win系统，刚刚重装了一下，还是不起作用。

**Comment by boomker** [comment]
这个问题解决了，稍晚推送更新
